#!/usr/bin/env python3
"""Regenerate the aggregate BEDC Lean import file."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


HEADER = (
    "-- AUTO-GENERATED by lean4/scripts/regenerate_bedc_lean.py — do not edit.\n"
    "-- Run `python3 lean4/scripts/regenerate_bedc_lean.py` to regenerate.\n"
    "\n"
)


def _find_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "lean4").is_dir():
            return candidate
    return start


def _module_name(path: Path, lean_root: Path) -> str:
    rel = path.relative_to(lean_root).with_suffix("")
    return ".".join(rel.parts)


def _desired_content(root: Path) -> tuple[str, int]:
    lean_root = root / "lean4"
    bedc_dir = lean_root / "BEDC"
    modules = sorted({
        _module_name(path, lean_root)
        for path in bedc_dir.rglob("*.lean")
        if path.is_file()
    })
    imports = "".join(f"import {module}\n" for module in modules)
    return HEADER + imports, len(modules)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate lean4/BEDC.lean.")
    parser.add_argument("--check", action="store_true", help="Check for drift without writing.")
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Repository root override.",
    )
    args = parser.parse_args(argv)

    script_root = Path(__file__).resolve().parents[2]
    root = (args.root.resolve() if args.root else _find_root(script_root)).resolve()
    target = root / "lean4" / "BEDC.lean"
    desired, count = _desired_content(root)

    if args.check:
        try:
            current = target.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current == desired:
            print(f"regenerated lean4/BEDC.lean ({count} imports)")
            return 0
        print("lean4/BEDC.lean is out of date", file=sys.stderr)
        return 1

    target.write_text(desired, encoding="utf-8")
    print(f"regenerated lean4/BEDC.lean ({count} imports)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
