#!/usr/bin/env python3
"""Run the seed-count convergence experiment for the Gaussian-OU runner."""

from __future__ import annotations

from datetime import datetime, timezone
import json
import math
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.experiment_stats import (
    estimate_min_k_for_ci,
    fit_ci_halfwidth_decay,
    prefix_metric_stats,
)
from scripts.run_gaussian_ou_lejepa import run_experiment


SAMPLE_COUNT = 384
RHO = 0.82
K_MAX = 40
K_GRID = (5, 10, 20, 40)
MASTER_SEED = 466021
TARGET_METRIC = "linear_identifiability_r2"
SLOPE_ACCEPTANCE_INTERVAL = (-0.8, -0.3)
TARGET_CI95_HALF_WIDTH = 0.02
LATE_MEAN_DELTA_THRESHOLD = TARGET_CI95_HALF_WIDTH
USE_TORCH = True
JSON_ARTIFACT = "reports/seed_count_convergence.json"
REPORT_ARTIFACT = "reports/seed_count_convergence.md"
METHOD = "prefix_of_deterministic_seed_sequence"


def _child_seed(master_seed: int, seed_index: int) -> int:
    value = (
        int(master_seed) * 1664525
        + 1013904223
        + int(seed_index) * 2246822519
        + int(seed_index) * int(seed_index) * 3266489917
    )
    return int(value % (2**32))


def _seeds(master_seed: int = MASTER_SEED, count: int = K_MAX) -> list[int]:
    return [_child_seed(master_seed, index) for index in range(count)]


def _run_record(*, seed: int, seed_index: int) -> dict[str, Any]:
    run_id = f"seed-count-convergence-seed-{seed}"
    envelope = run_experiment(
        use_torch=USE_TORCH,
        sample_count=SAMPLE_COUNT,
        rho=RHO,
        seed=seed,
        run_id=run_id,
        envelope_artifact=JSON_ARTIFACT,
        report_artifact=REPORT_ARTIFACT,
    )
    envelope_dict = envelope.to_dict()
    return {
        "seed_index": int(seed_index),
        "seed_sequence_position": int(seed_index + 1),
        "seed": int(seed),
        "sample_count": SAMPLE_COUNT,
        "rho": RHO,
        "run_id": run_id,
        "classifier_name": envelope.classifier_spec.get("name"),
        "classifier_training": envelope.classifier_spec.get("training"),
        "source_spec": dict(envelope.source_spec),
        "metrics": {name: float(value) for name, value in envelope.metrics.items()},
        "envelope": envelope_dict,
    }


def _records() -> list[dict[str, Any]]:
    return [_run_record(seed=seed, seed_index=index) for index, seed in enumerate(_seeds())]


def _validated_k_grid() -> list[int]:
    grid = sorted({int(k) for k in K_GRID if 0 < int(k) <= K_MAX})
    if len(grid) < 4 or grid[-1] < K_MAX:
        raise ValueError("K_GRID must include at least four positive entries up to K_MAX")
    return grid


def _target_values(records: list[dict[str, Any]]) -> list[float]:
    return [float(record["metrics"][TARGET_METRIC]) for record in records]


def _running_stats(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return prefix_metric_stats(_target_values(records), _validated_k_grid())


def _convergence_deltas(running_stats: list[dict[str, Any]]) -> dict[str, Any]:
    deltas = []
    ok_rows = [row for row in running_stats if row.get("status") == "ok"]
    for earlier, later in zip(ok_rows, ok_rows[1:]):
        delta = abs(float(later["mean"]) - float(earlier["mean"]))
        deltas.append(
            {
                "from_k": int(earlier["k"]),
                "to_k": int(later["k"]),
                "mean_delta": float(delta),
                "within_threshold": bool(delta <= LATE_MEAN_DELTA_THRESHOLD),
            }
        )
    late_delta = deltas[-1] if deltas else None
    return {
        "metric": TARGET_METRIC,
        "method": "adjacent_prefix_mean_delta",
        "late_mean_delta_threshold": LATE_MEAN_DELTA_THRESHOLD,
        "deltas": deltas,
        "late_adjacent_mean_delta_within_threshold": bool(
            late_delta is not None and late_delta["within_threshold"]
        ),
    }


def _ci_decay_fit(running_stats: list[dict[str, Any]]) -> dict[str, Any]:
    fit = fit_ci_halfwidth_decay(running_stats)
    return {
        **fit,
        "slope_acceptance_interval": list(SLOPE_ACCEPTANCE_INTERVAL),
        "slope_in_acceptance_interval": bool(
            fit["status"] == "ok"
            and SLOPE_ACCEPTANCE_INTERVAL[0] <= float(fit["slope"]) <= SLOPE_ACCEPTANCE_INTERVAL[1]
        ),
    }


def _minimum_k_estimate(
    running_stats: list[dict[str, Any]],
    ci_decay_fit: dict[str, Any],
) -> dict[str, Any]:
    return estimate_min_k_for_ci(
        running_stats,
        target_ci95_half_width=TARGET_CI95_HALF_WIDTH,
        decay_fit=ci_decay_fit,
    )


def _applicability_boundary() -> dict[str, Any]:
    return {
        "admitted_family": "Gaussian-OU toy world generated by the canonical runner",
        "method": METHOD,
        "seed_sequence": "deterministic child seeds from one master seed; prefixes reuse the same order",
        "sample_count": SAMPLE_COUNT,
        "rho": RHO,
        "k_grid": list(_validated_k_grid()),
        "metric_scope": f"finite `{TARGET_METRIC}` values returned by canonical quality envelopes",
        "non_claim": "does not claim independent re-draws for each prefix K",
    }


def _source_artifacts() -> dict[str, Any]:
    return {
        "generation_script": "scripts/run_seed_count_convergence.py",
        "canonical_runner": "scripts/run_gaussian_ou_lejepa.py::run_experiment",
        "stats_helper": "scripts/experiment_stats.py",
        "import_dependency_chain": [
            "scripts/run_seed_count_convergence.py",
            "scripts/run_gaussian_ou_lejepa.py::run_experiment",
            "scripts/experiment_stats.py",
            "bedc_quality_lab.toy_world.make_toy_batch",
            "bedc_quality_lab.metrics.metric_bundle",
            "bedc_quality_lab.schema.QualityEvidenceEnvelope",
        ],
        "json_artifact": JSON_ARTIFACT,
        "report_artifact": REPORT_ARTIFACT,
    }


def _payload(records: list[dict[str, Any]]) -> dict[str, Any]:
    running_stats = _running_stats(records)
    ci_fit = _ci_decay_fit(running_stats)
    return {
        "artifact": JSON_ARTIFACT,
        "report": REPORT_ARTIFACT,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "config": {
            "sample_count": SAMPLE_COUNT,
            "rho": RHO,
            "k_max": K_MAX,
            "k_grid": list(_validated_k_grid()),
            "master_seed": MASTER_SEED,
            "seeds": _seeds(),
            "method": METHOD,
            "target_metric": TARGET_METRIC,
            "target_ci95_half_width": TARGET_CI95_HALF_WIDTH,
            "slope_acceptance_interval": list(SLOPE_ACCEPTANCE_INTERVAL),
            "use_torch": USE_TORCH,
        },
        "source_artifacts": _source_artifacts(),
        "applicability_boundary": _applicability_boundary(),
        "records": records,
        "aggregate": {
            "record_count": len(records),
            "seed_order": [int(record["seed"]) for record in records],
            "target_metric_values": _target_values(records),
            "running_stats": running_stats,
            "convergence_deltas": _convergence_deltas(running_stats),
            "ci_decay_fit": ci_fit,
            "minimum_k_estimate": _minimum_k_estimate(running_stats, ci_fit),
        },
    }


def _format_float(value: float) -> str:
    if math.isnan(value):
        return "nan"
    return f"{value:.6f}"


def _pass_label(value: bool) -> str:
    return "pass" if value else "fail"


def _format_inline_value(value: Any) -> str:
    return json.dumps(value, sort_keys=True)


def _render_report(payload: dict[str, Any]) -> str:
    aggregate = payload["aggregate"]
    fit = aggregate["ci_decay_fit"]
    estimate = aggregate["minimum_k_estimate"]
    convergence = aggregate["convergence_deltas"]
    interval = payload["config"]["slope_acceptance_interval"]
    lines = [
        "# Seed-Count Convergence Experiment",
        "",
        f"- Generated at: `{payload['generated_at']}`",
        f"- Canonical runner: `{payload['source_artifacts']['canonical_runner']}`",
        f"- Method: `{payload['config']['method']}`",
        f"- Sample count: `{payload['config']['sample_count']}`",
        f"- Rho: `{payload['config']['rho']}`",
        f"- K grid: `{', '.join(str(k) for k in payload['config']['k_grid'])}`",
        f"- Master seed: `{payload['config']['master_seed']}`",
        f"- Target metric: `{payload['config']['target_metric']}`",
        f"- Total records: `{aggregate['record_count']}`",
        "",
        "## Prefix CI Table",
        "",
        "| K | mean | std | 95% CI half-width | 95% CI low | 95% CI high | status |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for row in aggregate["running_stats"]:
        lines.append(
            "| "
            f"{int(row['k'])} | "
            f"{_format_float(float(row['mean']))} | "
            f"{_format_float(float(row['std']))} | "
            f"{_format_float(float(row['ci95_half_width']))} | "
            f"{_format_float(float(row['ci95_low']))} | "
            f"{_format_float(float(row['ci95_high']))} | "
            f"`{row['status']}` |"
        )

    lines.extend(
        [
            "",
            "## Convergence Deltas",
            "",
            "| from K | to K | adjacent mean delta | within threshold |",
            "| ---: | ---: | ---: | --- |",
        ]
    )
    for row in convergence["deltas"]:
        lines.append(
            "| "
            f"{row['from_k']} | {row['to_k']} | "
            f"{_format_float(float(row['mean_delta']))} | "
            f"`{_pass_label(bool(row['within_threshold']))}` |"
        )

    lines.extend(
        [
            "",
            "## CI Half-Width Decay",
            "",
            f"- Fit status: `{fit['status']}`",
            (
                f"- Log-log slope: `{_format_float(float(fit['slope']))}` "
                f"(95% CI `{_format_float(float(fit['slope_ci95_low']))}` "
                f"to `{_format_float(float(fit['slope_ci95_high']))}`)"
            ),
            f"- Accepted slope interval: `[{interval[0]}, {interval[1]}]`",
            (
                f"- Slope interval result: "
                f"`{_pass_label(bool(fit['slope_in_acceptance_interval']))}`"
            ),
            (
                f"- Expected decay interval result: "
                f"`{_pass_label(bool(fit['slope_in_expected_interval']))}`"
            ),
            "",
            "## Minimum K Estimate",
            "",
            f"- Target 95% CI half-width: `{payload['config']['target_ci95_half_width']}`",
            f"- Estimate status: `{estimate['status']}`",
            f"- Method: `{estimate['method']}`",
            f"- Estimated K: `{estimate['estimated_k']}`",
            f"- Observed achievement: `{_pass_label(bool(estimate['achieved_observed']))}`",
            "",
            "## Applicability Boundary",
            "",
        ]
    )
    for key, value in payload["applicability_boundary"].items():
        lines.append(f"- {key}: `{_format_inline_value(value)}`")
    lines.extend(
        [
            "",
            "## Source Artifacts",
            "",
            f"- Generation script: `{payload['source_artifacts']['generation_script']}`",
            f"- JSON artifact: `{payload['source_artifacts']['json_artifact']}`",
            f"- Report artifact: `{payload['source_artifacts']['report_artifact']}`",
            f"- Stats helper: `{payload['source_artifacts']['stats_helper']}`",
            "- Import dependency chain:",
        ]
    )
    for item in payload["source_artifacts"]["import_dependency_chain"]:
        lines.append(f"  - `{item}`")
    lines.extend(
        [
            "",
            "## Seed Order",
            "",
            f"`{', '.join(str(seed) for seed in aggregate['seed_order'])}`",
            "",
        ]
    )
    return "\n".join(lines)


def _write_payload(payload: dict[str, Any]) -> None:
    json_path = ROOT / JSON_ARTIFACT
    report_path = ROOT / REPORT_ARTIFACT
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_path.write_text(_render_report(payload), encoding="utf-8")


def main() -> None:
    payload = _payload(_records())
    _write_payload(payload)
    print(f"wrote {JSON_ARTIFACT}")
    print(f"wrote {REPORT_ARTIFACT}")


if __name__ == "__main__":
    main()
