key = 'complextopology'

aliases = ['ComplexTopologyUp']

[en]
label = 'ComplexTopology'
desc = 'Topological structure on ComplexUp; opens / paths / connectedness.'
wiki = 'https://en.wikipedia.org/wiki/Topology'

[zh]
label = '复拓扑'
desc = 'ComplexUp 上的拓扑结构; 开集/路径/连通.'
wiki = 'https://zh.wikipedia.org/wiki/%E6%8B%93%E6%89%91%E5%AD%A6'
