key = 'complexanalytic'

aliases = ['ComplexAnalyticUp']

[en]
label = 'ComplexAnalytic'
desc = 'Complex analytic = holomorphic; locally convergent power series in z.'

[zh]
label = '复解析'
desc = '复解析 = 全纯; z 中的局部收敛幂级数.'
