key = 'contour'

aliases = ['ContourUp']

[en]
label = 'Contour'
desc = 'Contour integration as operation on holomorphic functions.'
wiki = 'https://en.wikipedia.org/wiki/Contour_integration'

[zh]
label = '围道积分'
desc = '围道积分, 作为全纯函数上的操作.'
wiki = 'https://zh.wikipedia.org/wiki/%E5%9B%B4%E9%81%93%E7%A7%AF%E5%88%86'
