key = 'empty'

aliases = ['EmptyUp']

[en]
label = 'Empty'
desc = 'Empty type / initial object; no inhabitants.'
wiki = 'https://en.wikipedia.org/wiki/Empty_type'

[zh]
label = '空类型'
desc = '空类型 / 始对象; 无居留元.'
wiki = 'https://zh.wikipedia.org/wiki/%E7%A9%BA%E7%B1%BB%E5%9E%8B'
