key = 'enrichedcat'

aliases = ['EnrichedCatUp']

[en]
label = 'EnrichedCat'
desc = 'Objects with hom-objects in a fixed monoidal category.'
wiki = 'https://en.wikipedia.org/wiki/Enriched_category'

[zh]
label = '富化范畴'
desc = '态射对象取值于固定幺半范畴的范畴.'
