key = 'ergodic'

aliases = ['ErgodicUp']

[en]
label = 'Ergodic'
desc = 'Measure-preserving transformation; ergodic decomposition of invariant subspaces.'

[zh]
label = '遍历理论'
desc = '保测变换及其不变子空间的遍历分解.'
