key = 'filter'

aliases = ['FilterUp']

[en]
label = 'Filter'
desc = 'Filter on a set; prefilter, proper filter, ultrafilter.'
wiki = 'https://en.wikipedia.org/wiki/Filter_%28mathematics%29'

[zh]
label = '滤子'
desc = '集合上的滤子; prefilter, proper filter, ultrafilter.'
wiki = 'https://zh.wikipedia.org/wiki/%E6%BB%A4%E5%AD%90_%28%E6%95%B0%E5%AD%A6%29'
