key = 'filter'

aliases = ['FilterUp']

[en]
label = 'Filter'
desc = 'Filter on a set; prefilter, proper filter, ultrafilter.'

[zh]
label = '滤子'
desc = '集合上的滤子; prefilter, proper filter, ultrafilter.'
