key = 'func'

aliases = ['FuncUp']

[en]
label = 'Func'
desc = 'Function interface; generic Hist-to-Hist mapping.'
wiki = 'https://en.wikipedia.org/wiki/Function_%28mathematics%29'

[zh]
label = '函数接口'
desc = '函数接口; 通用 Hist→Hist 映射.'
wiki = 'https://zh.wikipedia.org/wiki/%E5%87%BD%E6%95%B0'
