key = 'mirrorsymmetry'

aliases = ['MirrorSymmetryUp']

[en]
label = 'MirrorSymmetry'
desc = 'For a Calabi-Yau pair (X, X^∨), the A-model on one side ↔ the B-model on the other.'
wiki = 'https://en.wikipedia.org/wiki/Mirror_symmetry_%28string_theory%29'

[zh]
label = '镜像对称'
desc = 'Calabi-Yau 对 (X, X^∨) 间 A-模型 ↔ B-模型.'
wiki = 'https://zh.wikipedia.org/wiki/%E9%95%9C%E5%AF%B9%E7%A7%B0_%28%E5%BC%A6%E8%AE%BA%29'
