key = 'monad'

aliases = ['MonadUp']

[en]
label = 'Monad'
desc = 'Monoidal endofunctor with unit and multiplication.'
wiki = 'https://en.wikipedia.org/wiki/Monad_%28functional_programming%29'

[zh]
label = 'monad'
desc = '带单位和乘法的 monoidal endofunctor.'
wiki = 'https://zh.wikipedia.org/wiki/%E5%8D%95%E5%AD%90_%28%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B%29'
