key = 'mul'

aliases = ['MulUp']

[en]
label = 'Mul'
desc = 'Multiplicative monoid interface.'
wiki = 'https://en.wikipedia.org/wiki/Multiplication'

[zh]
label = '乘法接口'
desc = '乘法 monoid 接口.'
wiki = 'https://zh.wikipedia.org/wiki/%E4%B9%98%E6%B3%95'
