key = 'realanalytic'

aliases = ['RealAnalyticUp']

[en]
label = 'RealAnalytic'
desc = 'Real analytic functions on R; convergent power series locally.'
wiki = 'https://en.wikipedia.org/wiki/Analytic_function'

[zh]
label = '实解析'
desc = 'R 上的实解析函数; 局部收敛幂级数.'
wiki = 'https://zh.wikipedia.org/wiki/%E8%A7%A3%E6%9E%90%E5%87%BD%E6%95%B0'
