key = 'topvecspace'

aliases = ['TopVecSpaceUp']

[en]
label = 'TopVecSpace'
desc = 'Vector space with Hausdorff topology making addition and scalar multiplication continuous.'

[zh]
label = '拓扑向量空间'
desc = 'Hausdorff 拓扑下加法与数乘连续的向量空间.'
