key = 'transcendence'

aliases = ['TranscendenceUp']

[en]
label = 'Transcendence'
desc = 'Supremum of cardinalities of algebraically independent subsets.'

[zh]
label = '超越次数'
desc = '代数独立子集基数的上确界.'
