key = 'vonneumannalgebra'

aliases = ['VonNeumannAlgUp']

[en]
label = 'VonNeumannAlg'
desc = 'Unital *-subalgebra of B(H) closed in the weak operator topology.'

[zh]
label = '冯诺依曼代数'
desc = 'B(H) 中弱算子拓扑封闭的酉 *-子代数.'
