key = 'vonneumannalgebra'

aliases = ['VonNeumannAlgUp']

[en]
label = 'VonNeumannAlg'
desc = 'Unital *-subalgebra of B(H) closed in the weak operator topology.'
wiki = 'https://en.wikipedia.org/wiki/Von_Neumann_algebra'

[zh]
label = '冯诺依曼代数'
desc = 'B(H) 中弱算子拓扑封闭的酉 *-子代数.'
wiki = 'https://zh.wikipedia.org/wiki/%E5%86%AF%E8%AF%BA%E4%BE%9D%E6%9B%BC%E4%BB%A3%E6%95%B0'
