key = 'zeta'

aliases = ['ZetaUp']

[en]
label = 'Zeta'
desc = 'Riemann zeta function umbrella interface (basic + cont + zeros).'
wiki = 'https://en.wikipedia.org/wiki/Riemann_zeta_function'

[zh]
label = 'ζ 函数'
desc = 'Riemann zeta 函数综合接口(基础+延拓+零点).'
wiki = 'https://zh.wikipedia.org/wiki/%E9%BB%8E%E6%9B%BC%CE%B6%E5%87%BD%E6%95%B0'
