key = 'zetazeros'

aliases = ['ZetaZerosUp']

[en]
label = 'ZetaZeros'
desc = 'Zero predicate of zeta; trivial vs non-trivial zeros.'
wiki = 'https://en.wikipedia.org/wiki/Riemann_hypothesis'

[zh]
label = 'ζ 零点'
desc = 'zeta 零点谓词; 平凡零点 vs 非平凡零点.'
wiki = 'https://zh.wikipedia.org/wiki/%E9%BB%8E%E6%9B%BC%E7%8C%9C%E6%83%B3'
