namespace BEDC.Derived.MetaCICClosedNormalJoinCertificateUp

inductive MetaCICClosedNormalJoinCertificateUp where
  | closedNormalAtomFragmentCertificate

end BEDC.Derived.MetaCICClosedNormalJoinCertificateUp

