import BEDC.Manifest.Core
import BEDC.BaseReflection
import BEDC.FKernel.Gap
import BEDC.GroundCompiler
import BEDC.Derived.HolonomyUp
import BEDC.Derived.KKTUp
import BEDC.Derived.SpectralMeasureUp
import BEDC.Reflection
import BEDC.Capstone.EmptyFableMachine

namespace BEDC.Manifest

def manifest : List ClaimEntry := [
  ⟨"sec:base-reflection-lean-scaffold-contract",
    "BEDC.BaseReflection.PackageReflection_base",
    _, @BEDC.BaseReflection.PackageReflection_base⟩,
  ⟨"TBD",
    "BEDC.BaseReflection.PackageReflection_base_witness_chain",
    _, @BEDC.BaseReflection.PackageReflection_base_witness_chain⟩,
  ⟨"TBD",
    "BEDC.BaseReflection.PackageReflection_base_three_step_chain",
    _, @BEDC.BaseReflection.PackageReflection_base_three_step_chain⟩,
  ⟨"TBD",
    "BEDC.BaseReflection.TokUnique_replacement",
    _, @BEDC.BaseReflection.TokUnique_replacement⟩,
  ⟨"TBD",
    "BEDC.BaseReflection.PsameBase_iff_constructor_witnesses",
    _, @BEDC.BaseReflection.PsameBase_iff_constructor_witnesses⟩,
  ⟨"TBD",
    "BEDC.BaseReflection.GeneratedSameSig_iff_witnesses",
    _, @BEDC.BaseReflection.GeneratedSameSig_iff_witnesses⟩,
  ⟨"sec:base-reflection-lean-scaffold-contract",
    "BEDC.BaseReflection.no_scaffold_laundering_coverage_soundness",
    _, @BEDC.BaseReflection.no_scaffold_laundering_coverage_soundness⟩,

  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.channel_bijection",
    _, @BEDC.GroundCompiler.MainTheorems.channel_bijection⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.channel_code_lossless",
    _, @BEDC.GroundCompiler.MainTheorems.channel_code_lossless⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.code_not_proof",
    _, @BEDC.GroundCompiler.MainTheorems.code_not_proof⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.global_conservativity",
    _, @BEDC.GroundCompiler.MainTheorems.global_conservativity⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.no_self_compilation_without_ledger",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.no_self_compilation_without_ledger⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.self_compilation_preserves_provenance",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.self_compilation_preserves_provenance⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.DerivCertReports.p6_adequacy",
    _, @BEDC.GroundCompiler.DerivCertReports.p6_adequacy⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.TheoremProofPrototype.p7_adequacy",
    _, @BEDC.GroundCompiler.TheoremProofPrototype.p7_adequacy⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.formal_compilation_requires_certificate",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.formal_compilation_requires_certificate⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.uncertified_cannot_compile",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.uncertified_cannot_compile⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.bootstrap_must_be_explicit",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.bootstrap_must_be_explicit⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.hidden_bootstrap_violates",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.hidden_bootstrap_violates⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.self_hosting_yields_behavior_classifier",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.self_hosting_yields_behavior_classifier⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.self_hosting_requires_ledger",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.self_hosting_requires_ledger⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.self_hosting_removes_hidden_input",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.self_hosting_removes_hidden_input⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.fully_discharged_supports_full_claim",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.fully_discharged_supports_full_claim⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.remaining_bootstrap_boundary_visible",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.remaining_bootstrap_boundary_visible⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.SelfHostingCompilerFlow.channel_correctness_separate",
    _, @BEDC.GroundCompiler.SelfHostingCompilerFlow.channel_correctness_separate⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.ImplementationAdequacy.implementation_adequacy",
    _, @BEDC.GroundCompiler.ImplementationAdequacy.implementation_adequacy⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.ImplementationAdequacy.passing_tests_weaker_than_adequacy",
    _, @BEDC.GroundCompiler.ImplementationAdequacy.passing_tests_weaker_than_adequacy⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.no_hidden_input",
    _, @BEDC.GroundCompiler.MainTheorems.no_hidden_input⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.source_channel_separation",
    _, @BEDC.GroundCompiler.MainTheorems.source_channel_separation⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.carry_not_channel_rewrite",
    _, @BEDC.GroundCompiler.MainTheorems.carry_not_channel_rewrite⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.structure_emergence",
    _, @BEDC.GroundCompiler.MainTheorems.structure_emergence⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.yaml_ast_output_only",
    _, @BEDC.GroundCompiler.MainTheorems.yaml_ast_output_only⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.recognizer_generatedness",
    _, @BEDC.GroundCompiler.MainTheorems.recognizer_generatedness⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.accepted_export",
    _, @BEDC.GroundCompiler.MainTheorems.accepted_export⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.code_existence_not_export",
    _, @BEDC.GroundCompiler.MainTheorems.code_existence_not_export⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.motif_existence_not_export",
    _, @BEDC.GroundCompiler.MainTheorems.motif_existence_not_export⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.theorem_code_bijection",
    _, @BEDC.GroundCompiler.MainTheorems.theorem_code_bijection⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.proposition_not_theorem_code",
    _, @BEDC.GroundCompiler.MainTheorems.proposition_not_theorem_code⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.theorem_code_not_proof",
    _, @BEDC.GroundCompiler.MainTheorems.theorem_code_not_proof⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.chapter_code_bijection",
    _, @BEDC.GroundCompiler.MainTheorems.chapter_code_bijection⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.classifier_quotient_many_to_one",
    _, @BEDC.GroundCompiler.MainTheorems.classifier_quotient_many_to_one⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.normal_address_requires_ledger",
    _, @BEDC.GroundCompiler.MainTheorems.normal_address_requires_ledger⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.declared_bootstrap_boundary",
    _, @BEDC.GroundCompiler.MainTheorems.declared_bootstrap_boundary⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.metric_conservativity",
    _, @BEDC.GroundCompiler.MainTheorems.metric_conservativity⟩,
  ⟨"TBD",
    "BEDC.GroundCompiler.MainTheorems.no_hidden_input_streaming_compiler",
    _, @BEDC.GroundCompiler.MainTheorems.no_hidden_input_streaming_compiler⟩,

  ⟨"TBD",
    "BEDC.Derived.HolonomyUp.HolonomyTransportPacket_namecert_obligation_surface",
    _, @BEDC.Derived.HolonomyUp.HolonomyTransportPacket_namecert_obligation_surface⟩,
  ⟨"TBD",
    "BEDC.Derived.KKTUp.KKTPrimalDualPacket_namecert_obligation_surface",
    _, @BEDC.Derived.KKTUp.KKTPrimalDualPacket_namecert_obligation_surface⟩,
  ⟨"TBD",
    "BEDC.Derived.SpectralMeasureUp.SpectralMeasureFinitePacket_namecert_obligation_surface",
    _, @BEDC.Derived.SpectralMeasureUp.SpectralMeasureFinitePacket_namecert_obligation_surface⟩,

  ⟨"TBD",
    "BEDC.FKernel.Gap.domain_transport",
    _, @BEDC.FKernel.Gap.domain_transport⟩,
  ⟨"TBD",
    "BEDC.FKernel.Gap.DomainPolicy_iff_transport",
    _, @BEDC.FKernel.Gap.DomainPolicy_iff_transport⟩,
  ⟨"TBD",
    "BEDC.FKernel.Gap.DomainPolicy_iff_transport_and_invariance",
    _, @BEDC.FKernel.Gap.DomainPolicy_iff_transport_and_invariance⟩,
  ⟨"TBD",
    "BEDC.FKernel.Gap.inGapSig_transport_iff_with_signature_witnesses",
    _, @BEDC.FKernel.Gap.inGapSig_transport_iff_with_signature_witnesses⟩,
  ⟨"sec:proof-sprint-globalization-classifies-by-signatures",
    "BEDC.FKernel.Gap.proof_sprint_globalization_classifies_by_signatures",
    _, @BEDC.FKernel.Gap.proof_sprint_globalization_classifies_by_signatures⟩,
  ⟨"sec:proof-spine-composite-gap-coverage",
    "BEDC.FKernel.Gap.proof_spine_composite_gap_coverage",
    _, @BEDC.FKernel.Gap.proof_spine_composite_gap_coverage⟩,
  ⟨"sec:ledger-composition-principle-proof-standing",
    "BEDC.FKernel.Gap.ledger_composition_principle_proof_standing",
    _, @BEDC.FKernel.Gap.ledger_composition_principle_proof_standing⟩,

  ⟨"sec:empty-fable-machine-traces",
    "BEDC.Capstone.EmptyFableMachine.trace_hsame_transport",
    _, @BEDC.Capstone.EmptyFableMachine.trace_hsame_transport⟩,
  ⟨"sec:empty-fable-machine-ledger",
    "BEDC.Capstone.EmptyFableMachine.fable_ledger_sound",
    _, @BEDC.Capstone.EmptyFableMachine.fable_ledger_sound⟩,
  ⟨"sec:type-checking-as-classifier-membership",
    "BEDC.Reflection.type_checking_as_ext_membership_proof",
    _, @BEDC.Reflection.type_checking_as_ext_membership_proof⟩,
  ⟨"sec:compilation-as-namecert-morphism",
    "BEDC.Reflection.compilation_as_namecert_morphism_proof",
    _, @BEDC.Reflection.compilation_as_namecert_morphism_proof⟩
]

/-- Wellformedness 的可观察推论: manifest 里每条 claim 都至少有一个证明 witness。
    实质内容由 Lean 在 elaborate `manifest` 时做的 type-check 承载 (依赖字段 proof : prop)。 -/
theorem manifest_wellformed : ∀ e ∈ manifest, Nonempty e.prop :=
  fun e _ => ⟨e.proof⟩

end BEDC.Manifest
