import UnifiedTheory.Golden.PhiInt

/-!
# φ-discrete coordinate system over `ℤ[φ]`

This file records the L0 coordinate-ring facts used by the golden coordinate
system: the concrete commutative ring structure, the integral norm, conjugation,
and the unit generated by `φ`.
-/

namespace UnifiedTheory
namespace PhiInt

@[simp] theorem neg_a (x : PhiInt) : (-x).a = -x.a := rfl
@[simp] theorem neg_b (x : PhiInt) : (-x).b = -x.b := rfl
@[simp] theorem sub_a (x y : PhiInt) : (x - y).a = x.a - y.a := rfl
@[simp] theorem sub_b (x y : PhiInt) : (x - y).b = x.b - y.b := rfl

instance : CommRing PhiInt where
  nsmul := fun n x => ⟨(n : ℤ) * x.a, (n : ℤ) * x.b⟩
  zsmul := fun n x => ⟨n * x.a, n * x.b⟩
  add_assoc x y z := by
    simp only [ext_iff, add_a, add_b]
    constructor <;> ring
  zero_add x := by
    simp only [ext_iff, zero_a, zero_b, add_a, add_b]
    constructor <;> ring
  add_zero x := by
    simp only [ext_iff, zero_a, zero_b, add_a, add_b]
    constructor <;> ring
  nsmul_zero x := by
    simp only [ext_iff, zero_a, zero_b]
    constructor <;> ring
  nsmul_succ n x := by
    simp only [ext_iff, add_a, add_b]
    constructor <;> (norm_num [Nat.cast_succ]; ring)
  add_comm x y := by
    simp only [ext_iff, add_a, add_b]
    constructor <;> ring
  left_distrib x y z := by
    simp only [ext_iff, add_a, add_b, mul_a, mul_b]
    constructor <;> ring
  right_distrib x y z := by
    simp only [ext_iff, add_a, add_b, mul_a, mul_b]
    constructor <;> ring
  zero_mul x := by
    simp only [ext_iff, zero_a, zero_b, mul_a, mul_b]
    constructor <;> ring
  mul_zero x := by
    simp only [ext_iff, zero_a, zero_b, mul_a, mul_b]
    constructor <;> ring
  mul_assoc x y z := by
    simp only [ext_iff, mul_a, mul_b]
    constructor <;> ring
  one_mul x := by
    simp only [ext_iff, one_a, one_b, mul_a, mul_b]
    constructor <;> ring
  mul_one x := by
    simp only [ext_iff, one_a, one_b, mul_a, mul_b]
    constructor <;> ring
  npow_zero x := by
    rfl
  npow_succ n x := by
    rfl
  sub_eq_add_neg x y := by
    simp only [ext_iff, sub_a, sub_b, add_a, add_b, neg_a, neg_b]
    constructor <;> ring
  zsmul_zero' x := by
    simp only [ext_iff, zero_a, zero_b]
    constructor <;> ring
  zsmul_succ' n x := by
    simp only [ext_iff, add_a, add_b]
    constructor <;> (norm_num [Int.ofNat_eq_natCast, Nat.cast_succ]; ring)
  zsmul_neg' n x := by
    simp only [ext_iff, neg_a, neg_b]
    constructor <;> (norm_num [Int.negSucc_eq, Int.ofNat_eq_natCast, Nat.cast_succ]; ring)
  neg_add_cancel x := by
    simp only [ext_iff, zero_a, zero_b, add_a, add_b, neg_a, neg_b]
    constructor <;> ring
  intCast_ofNat n := by
    rfl
  intCast_negSucc n := by
    rfl
  mul_comm x y := by
    simp only [ext_iff, mul_a, mul_b]
    constructor <;> ring

/-- The integral norm `N(a + bφ) = a^2 + ab - b^2`. -/
def norm (x : PhiInt) : ℤ := x.a ^ 2 + x.a * x.b - x.b ^ 2

theorem norm_eq_mul_conj (x : PhiInt) : ofInt x.norm = x * conj x := by
  simp only [norm, ext_iff, ofInt_a, ofInt_b, mul_a, mul_b, conj_a, conj_b]
  constructor <;> ring

theorem norm_mul (x y : PhiInt) : (x * y).norm = x.norm * y.norm := by
  simp only [norm, mul_a, mul_b]
  ring

theorem conj_involutive : Function.Involutive conj := by
  intro x
  exact conj_conj x

@[simp] theorem conj_add (x y : PhiInt) : conj (x + y) = conj x + conj y := by
  simp only [ext_iff, conj_a, conj_b, add_a, add_b]
  constructor <;> ring

@[simp] theorem conj_mul (x y : PhiInt) : conj (x * y) = conj x * conj y := by
  simp only [ext_iff, conj_a, conj_b, mul_a, mul_b]
  constructor <;> ring

@[simp] theorem conj_one : conj 1 = 1 := by
  simp only [ext_iff, conj_a, conj_b, one_a, one_b]
  constructor <;> ring

def conjHom : PhiInt →+* PhiInt where
  toFun := conj
  map_one' := conj_one
  map_mul' := conj_mul
  map_zero' := by
    simp only [ext_iff, conj_a, conj_b, zero_a, zero_b]
    constructor <;> ring
  map_add' := conj_add

def conjAut : PhiInt ≃+* PhiInt where
  toFun := conj
  invFun := conj
  left_inv := conj_involutive
  right_inv := conj_involutive
  map_mul' := conj_mul
  map_add' := conj_add

@[simp] theorem norm_phi : phi.norm = -1 := by
  simp [norm, phi]

theorem isUnit_phi : IsUnit phi := by
  refine ⟨⟨phi, ⟨-1, 1⟩, ?_, ?_⟩, rfl⟩
  · simp only [ext_iff, phi, one_a, one_b, mul_a, mul_b]
    constructor <;> norm_num
  · simp only [ext_iff, phi, one_a, one_b, mul_a, mul_b]
    constructor <;> norm_num

@[simp] theorem norm_phiPow (n : ℕ) : (phiPow n).norm = (-1 : ℤ) ^ n := by
  induction n with
  | zero =>
      simp [phiPow, norm]
  | succ n ih =>
      rw [phiPow, norm_mul, ih, norm_phi, pow_succ]

end PhiInt
end UnifiedTheory
