#include "cook_encode.h"
#include "cyclic_tag.h"
#include "manifest_runner.h"
#include "rule110.h"

#include <assert.h>
#include <ctype.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define ROUND_TRIP_CT_STEPS 200
#define ROUND_TRIP_R110_STEPS 32
#define ROUND_TRIP_MANIFEST_PATH "tests/tmp_round_trip_msame_refl_enum.r110"

typedef struct {
    uint8_t **productions;
    size_t *prod_lens;
    size_t num_productions;
    uint8_t *tape;
    size_t tape_len;
} RoundTripCt;

static void round_trip_ct_init(RoundTripCt *ct) {
    ct->productions = NULL;
    ct->prod_lens = NULL;
    ct->num_productions = 0;
    ct->tape = NULL;
    ct->tape_len = 0;
}

static void round_trip_ct_free(RoundTripCt *ct) {
    for (size_t i = 0; i < ct->num_productions; i++) free(ct->productions[i]);
    free(ct->productions);
    free(ct->prod_lens);
    free(ct->tape);
    round_trip_ct_init(ct);
}

static char *trim_ascii(char *s) {
    char *end;

    while (*s && isspace((unsigned char)*s)) s++;
    end = s + strlen(s);
    while (end > s && isspace((unsigned char)end[-1])) end--;
    *end = '\0';
    return s;
}

static uint8_t *parse_bits(const char *s, size_t *out_len) {
    uint8_t *bits;
    size_t n = strlen(s);
    size_t len = 0;

    bits = (uint8_t *)malloc(n ? n : 1);
    assert(bits != NULL);

    for (size_t i = 0; i < n; i++) {
        if (s[i] == '0' || s[i] == '1') {
            bits[len++] = (uint8_t)(s[i] == '1');
        }
    }

    *out_len = len;
    return bits;
}

static int parse_productions_header(const char *line, size_t *out) {
    const char keyword[] = "PRODUCTIONS";
    char *endptr;
    unsigned long value;
    size_t keyword_len = sizeof(keyword) - 1;

    if (strncmp(line, keyword, keyword_len) != 0) return 0;
    if (!isspace((unsigned char)line[keyword_len])) return 0;

    value = strtoul(line + keyword_len, &endptr, 10);
    if (endptr == line + keyword_len) return 0;
    while (*endptr && isspace((unsigned char)*endptr)) endptr++;
    if (*endptr != '\0') return 0;

    *out = (size_t)value;
    return 1;
}

static int load_ct_manifest_for_round_trip(const char *path, RoundTripCt *out) {
    FILE *f = fopen(path, "r");
    char line[1024];
    int found_productions = 0;
    int found_tape = 0;

    if (!f) return -1;
    round_trip_ct_init(out);

    while (fgets(line, sizeof(line), f)) {
        char *trimmed = trim_ascii(line);
        size_t n;

        if (trimmed[0] == '\0' || trimmed[0] == '#') continue;

        if (!found_productions && parse_productions_header(trimmed, &n)) {
            out->num_productions = n;
            out->productions = (uint8_t **)calloc(n ? n : 1, sizeof(uint8_t *));
            out->prod_lens = (size_t *)calloc(n ? n : 1, sizeof(size_t));
            if (!out->productions || !out->prod_lens) {
                fclose(f);
                round_trip_ct_free(out);
                return -1;
            }

            for (size_t i = 0; i < n; i++) {
                if (!fgets(line, sizeof(line), f)) {
                    fclose(f);
                    round_trip_ct_free(out);
                    return -1;
                }
                trimmed = trim_ascii(line);
                out->productions[i] = parse_bits(trimmed, &out->prod_lens[i]);
            }
            found_productions = 1;
            continue;
        }

        if (!found_tape) {
            char *input = strstr(trimmed, "input=");
            if (input != NULL) {
                char *end;

                input += strlen("input=");
                while (*input && isspace((unsigned char)*input)) input++;
                end = input;
                while (*end == '0' || *end == '1') end++;
                *end = '\0';
                out->tape = parse_bits(input, &out->tape_len);
                found_tape = 1;
            }
        }
    }

    fclose(f);
    if (!found_productions || !found_tape) {
        round_trip_ct_free(out);
        return -1;
    }
    return 0;
}

static void write_bits(FILE *f, const uint8_t *bits, size_t len) {
    for (size_t i = 0; i < len; i++) fputc(bits[i] ? '1' : '0', f);
    fputc('\n', f);
}

static void write_r110_manifest(const char *path,
                                const uint8_t *initial,
                                const uint8_t *final,
                                size_t len,
                                size_t steps) {
    FILE *f = fopen(path, "w");

    assert(f != NULL);
    fprintf(f, "# Generated by test_round_trip.c\n");
    fprintf(f, "# Scaffold only: deterministic Rule 110 evolution, not CT semantic decoding.\n");
    fprintf(f, "INITIAL_PATTERN %zu\n", len);
    write_bits(f, initial, len);
    fprintf(f, "EVOLUTION_STEPS %zu\n", steps);
    fprintf(f, "EXPECTED_FINAL_PATTERN %zu\n", len);
    write_bits(f, final, len);
    assert(fclose(f) == 0);
}

static char *bits_to_cstr(const uint8_t *bits, size_t len) {
    char *s = (char *)malloc(len + 1);

    assert(s != NULL);
    for (size_t i = 0; i < len; i++) s[i] = bits[i] ? '1' : '0';
    s[len] = '\0';
    return s;
}

static void test_round_trip_msame_refl_enum(void) {
    const char *ct_path = "manifests/mark/msame_refl.enum.ct";
    RoundTripCt parsed;
    CyclicTagInput encode_input;
    uint8_t initial[4096] = {0};
    uint8_t final[4096] = {0};
    char *ct_input_bits;
    size_t written;
    MrResult ct_result;
    MrResult r110_result;

    assert(load_ct_manifest_for_round_trip(ct_path, &parsed) == 0);

    encode_input.productions = parsed.productions;
    encode_input.prod_lens = parsed.prod_lens;
    encode_input.num_productions = parsed.num_productions;
    encode_input.initial_tape = parsed.tape;
    encode_input.tape_len = parsed.tape_len;

    written = cook_encode(&encode_input, initial, sizeof(initial));
    assert(written > 0);
    assert(written <= sizeof(initial));

    memcpy(final, initial, written);
    r110_run_n_steps(final, written, ROUND_TRIP_R110_STEPS);
    write_r110_manifest(ROUND_TRIP_MANIFEST_PATH,
                        initial,
                        final,
                        written,
                        ROUND_TRIP_R110_STEPS);

    ct_input_bits = bits_to_cstr(parsed.tape, parsed.tape_len);
    ct_result = mr_run_ct_manifest(ct_path, ct_input_bits, "", ROUND_TRIP_CT_STEPS);
    r110_result = mr_run_r110_manifest(ROUND_TRIP_MANIFEST_PATH, 0);

    assert(ct_result == MR_PASS);
    assert(r110_result == MR_PASS);

    printf("  round_trip_msame_refl_enum: PASS "
           "(scaffold; r110_len=%zu steps=%d; correctness deferred)\n",
           written,
           ROUND_TRIP_R110_STEPS);

    free(ct_input_bits);
    round_trip_ct_free(&parsed);
    remove(ROUND_TRIP_MANIFEST_PATH);
}

int main(void) {
    printf("== test_round_trip ==\n");
    test_round_trip_msame_refl_enum();
    printf("ALL test_round_trip tests passed\n");
    return 0;
}
