#!/usr/bin/env python3
"""Reject external provenance leaked into BEDC paper body.

External source records, bridge records, URLs, local paths, and generator
identity are allowed as review metadata and candidate seeds. The BEDC paper
body must re-derive accepted material natively and must not cite those
metadata paths or source identities as mathematical evidence.
"""

from __future__ import annotations

import sys
from pathlib import Path


PAPER_DIR = Path(__file__).resolve().parents[1]
SCAN_ROOTS = [
    PAPER_DIR / "frontmatter",
    PAPER_DIR / "parts",
    PAPER_DIR / "appendices",
]

AI_NAMES = ("ChatGPT", "Claude", "OpenAI", "Anthropic")
ABS_PATH_MARKERS = ("/Users/", "/private/", "/tmp/", "/var/", "/opt/", "/home/")
SOURCE_KEY_PARTS = (
    ("source", "path"),
    ("source", "repo"),
    ("source", "commit"),
    ("source", "ref"),
    ("repository", "path"),
    ("repository", "repo"),
    ("repository", "commit"),
    ("repository", "ref"),
    ("repo", "path"),
    ("repo", "repo"),
    ("repo", "commit"),
    ("repo", "ref"),
)
TEXT_NEEDLES = (
    "Inspired by Omega Project",
    "automath",
    "Automath",
    "discovery",
    "report.json",
    "automath_newmath_bridge",
    "review_packets",
    "http://",
    "https://",
    "github.com",
    "GitHub.com",
    "arxiv",
    "arXiv",
    "Arxiv",
    "Wikipedia",
    "wikipedia",
    "ChatGPT",
    "Claude",
    "OpenAI",
    "Anthropic",
    "/Users/",
    "/private/",
    "/tmp/",
    "/var/",
    "/opt/",
    "/home/",
    "Generated",
    "generated",
    "Produced",
    "produced",
    "repository",
    "Repository",
    "repo",
    "Repo",
    "source_",
    "source-",
    "Source_",
    "Source-",
    "review packet",
    "Review packet",
    "bridge packet",
    "Bridge packet",
)
CANDIDATE_NEEDLES = (
    "Inspired by Omega Project",
    "automath",
    "Automath",
    "discovery",
    "report.json",
    "automath_newmath_bridge",
    "review_packets",
    "http://",
    "https://",
    "github.com",
    "GitHub.com",
    "arxiv",
    "arXiv",
    "Arxiv",
    "Wikipedia",
    "wikipedia",
    "ChatGPT",
    "Claude",
    "OpenAI",
    "Anthropic",
    "/Users/",
    "/private/",
    "/tmp/",
    "/var/",
    "/opt/",
    "/home/",
    "generated by",
    "Generated by",
    "produced by",
    "Produced by",
    "repository coordinates",
    "Repository coordinates",
    "repo coordinates",
    "Repo coordinates",
    "source_path",
    "source-path",
    "source_repo",
    "source-repo",
    "source_commit",
    "source-commit",
    "source_ref",
    "source-ref",
    "repository_path",
    "repository-path",
    "repository_repo",
    "repository-repo",
    "repository_commit",
    "repository-commit",
    "repository_ref",
    "repository-ref",
    "repo_path",
    "repo-path",
    "repo_repo",
    "repo-repo",
    "repo_commit",
    "repo-commit",
    "repo_ref",
    "repo-ref",
    "review packet path",
    "review packet json",
    "bridge packet path",
    "bridge packet json",
)


def has_word(text: str, word: str) -> bool:
    start = 0
    while True:
        idx = text.find(word, start)
        if idx == -1:
            return False
        left_ok = idx == 0 or not (text[idx - 1].isalnum() or text[idx - 1] == "_")
        end = idx + len(word)
        right_ok = end == len(text) or not (text[end].isalnum() or text[end] == "_")
        if left_ok and right_ok:
            return True
        start = idx + 1


def has_source_key(text: str) -> bool:
    for first, second in SOURCE_KEY_PARTS:
        for sep in ("_", "-"):
            token = f"{first}{sep}{second}"
            start = 0
            while True:
                idx = text.find(token, start)
                if idx == -1:
                    break
                left_ok = idx == 0 or not (text[idx - 1].isalnum() or text[idx - 1] == "_")
                end = idx + len(token)
                right_ok = end == len(text) or not (text[end].isalnum() or text[end] == "_")
                if left_ok and right_ok:
                    return True
                start = idx + 1
    return False


def leaks_external_provenance(line: str) -> bool:
    lower = line.lower()
    if "Inspired by Omega Project" in line:
        return True
    if has_word(line, "Automath") or has_word(line, "automath"):
        return True
    if "automath/" in line:
        return True
    if "discovery" in lower and "report.json" in lower:
        return True
    if "automath_newmath_bridge" in lower and "review_packets" in lower and ".json" in lower:
        return True
    if "review_packets" in lower and ".json" in lower:
        return True
    if "http://" in lower or "https://" in lower:
        return True
    if "github.com" in lower:
        return True
    if has_word(lower, "arxiv"):
        return True
    if has_word(lower, "wikipedia"):
        return True
    if any(name in line for name in AI_NAMES):
        return True
    if any(marker in line for marker in ABS_PATH_MARKERS):
        return True
    if ("generated by" in lower or "produced by" in lower) and any(
        name.lower() in lower for name in AI_NAMES
    ):
        return True
    if "repository coordinates" in lower or "repo coordinates" in lower:
        return True
    if has_source_key(lower):
        return True
    if (
        "review packet path" in lower
        or "review packet json" in lower
        or "bridge packet path" in lower
        or "bridge packet json" in lower
    ):
        return True
    return False


def iter_tex_files() -> list[Path]:
    files: list[Path] = []
    for root in SCAN_ROOTS:
        if root.exists():
            files.extend(sorted(root.rglob("*.tex")))
    return files


def main() -> int:
    violations: list[str] = []
    for path in iter_tex_files():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            violations.append(f"{path.relative_to(PAPER_DIR)}: read failed: {exc}")
            continue
        if not any(needle in text for needle in TEXT_NEEDLES):
            continue
        for line_no, line in enumerate(text.splitlines(), start=1):
            if not any(needle in line for needle in CANDIDATE_NEEDLES):
                continue
            if leaks_external_provenance(line):
                rel = path.relative_to(PAPER_DIR)
                violations.append(f"{rel}:{line_no}: external provenance leaked: {line.strip()[:220]}")

    if violations:
        print("External provenance check failed.", file=sys.stderr)
        print(
            "External source records, bridge packets, URLs, local paths, and "
            "generator identities are candidate metadata only; BEDC paper body "
            "must be re-derived natively.",
            file=sys.stderr,
        )
        for item in violations:
            print(item, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
