#!/usr/bin/env python3
"""Generate framework stubs for missing concrete-instance namecert chapters.

Produces a paper-only skeleton (chapter, label, intro paragraph, two section
headers) for each entry in CATALOG. Also emits the list of \\input lines for
main.tex and the list of \\newcommand declarations for any preamble macros
that do not yet exist.
"""

import pathlib
import re

ROOT = pathlib.Path("/Users/auric/newmath/papers/bedc")
DEST = ROOT / "parts" / "concrete_instances"
PREAMBLE = ROOT / "preamble.tex"
MAIN = ROOT / "main.tex"

CATALOG = [
    # (number, file_slug, macro, intro_paragraph)
    (56, "magma", "MagmaUp",
     "The magma interface $\\MagmaUp$ packages a carrier endowed with a single binary operation, with no associativity, identity, or inverse demands. It is the smallest algebraic naming certificate above the inductive carriers of \\autoref{ch:concrete-instances-bool-namecert}--\\autoref{ch:concrete-instances-list-namecert} and the entry point of the algebraic ladder culminating in $\\NameCert_{\\FieldUp}$ (\\autoref{ch:concrete-instances-field-namecert})."),
    (57, "semigroup", "SemigroupUp",
     "The semigroup interface $\\SemigroupUp$ adds associativity to $\\MagmaUp$ (\\autoref{ch:concrete-instances-magma-namecert}). It sits between the magma layer and $\\NameCert_{\\MonoidUp}$ (\\autoref{ch:concrete-instances-monoid-namecert}), exposing the closure law that distinguishes free semigroups from arbitrary binary structures."),
    (58, "subgroup", "SubgroupUp",
     "The subgroup interface $\\SubgroupUp$ packages a subset of a group carrier closed under the group operation, identity, and inverse. It depends on $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert}) and is the first sub-object construction in BEDC, prerequisite to the quotient and ideal certificates that follow."),
    (59, "ideal", "IdealUp",
     "The ideal interface $\\IdealUp$ packages a sub-rng of a ring carrier closed under multiplication by every ambient ring element. It depends on $\\NameCert_{\\RingUp}$ (\\autoref{ch:concrete-instances-ring-namecert}) and supplies the kernel object for the quotient-ring construction $\\NameCert_{\\QuotientRingUp}$ (\\autoref{ch:concrete-instances-quotientring-namecert})."),
    (60, "quotientgroup", "QuotientGroupUp",
     "The quotient-group interface $\\QuotientGroupUp$ packages the carrier of cosets of a normal subgroup of a group. It depends on $\\NameCert_{\\SubgroupUp}$ (\\autoref{ch:concrete-instances-subgroup-namecert}) plus the normality witness, and produces a $\\psame$-classifier on cosets without invoking host-level $\\Quot$-soundness."),
    (61, "quotientring", "QuotientRingUp",
     "The quotient-ring interface $\\QuotientRingUp$ packages the carrier of cosets of an ideal in a ring. It depends on $\\NameCert_{\\IdealUp}$ (\\autoref{ch:concrete-instances-ideal-namecert}) and lifts $\\NameCert_{\\QuotientGroupUp}$ (\\autoref{ch:concrete-instances-quotientgroup-namecert}) to the multiplicative structure."),
    (62, "determinant", "DeterminantUp",
     "The determinant interface $\\DeterminantUp$ packages the alternating multilinear form on square matrices that detects invertibility. It depends on $\\NameCert_{\\MatrixUp}$ (\\autoref{ch:concrete-instances-matrix-namecert}) and $\\NameCert_{\\CommRingUp}$ (\\autoref{ch:concrete-instances-commring-namecert}), and supplies the invariant used by the eigenvalue and characteristic-polynomial certificates."),
    (63, "eigen", "EigenUp",
     "The eigen-pair interface $\\EigenUp$ packages an eigenvalue / eigenvector pair $(\\lambda, v)$ for a linear endomorphism. It depends on $\\NameCert_{\\LinearMapUp}$ (\\autoref{ch:concrete-instances-linearmap-namecert}) and $\\NameCert_{\\DeterminantUp}$ (\\autoref{ch:concrete-instances-determinant-namecert}), with $\\lambda$ certified as a root of the characteristic polynomial."),
    (64, "innerproduct", "InnerProductUp",
     "The inner-product interface $\\InnerProductUp$ packages a vector space together with a constructive sesquilinear form satisfying conjugate symmetry, linearity, and positive definiteness. It depends on $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}) and is the direct prerequisite for the Hilbert certificate $\\NameCert_{\\HilbertUp}$."),
    (65, "tensorproduct", "TensorProductUp",
     "The tensor-product interface $\\TensorProductUp$ packages the universal bilinear factorization of two module carriers. It depends on $\\NameCert_{\\ModuleUp}$ (\\autoref{ch:concrete-instances-module-namecert}) and supplies the multilinear data on which higher tensor algebras and exterior powers are built."),
    (66, "topology", "TopologyUp",
     "The topology interface $\\TopologyUp$ packages a carrier with a family of open subsets closed under finite intersections and arbitrary unions, certified by an explicit indexing of opens. It generalises $\\NameCert_{\\MetricSpaceUp}$ (\\autoref{ch:concrete-instances-metric-namecert}) by dropping the located-distance requirement and supplies the substrate for $\\NameCert_{\\BanachUp}$, $\\NameCert_{\\ManifoldUp}$, and the topological side of $\\NameCert_{\\ComplexTopologyUp}$ (\\autoref{ch:concrete-instances-complex-topology-namecert})."),
    (67, "norm", "NormUp",
     "The norm interface $\\NormUp$ packages a vector-space carrier with a constructive non-negative real-valued norm satisfying positive definiteness, absolute homogeneity, and the triangle inequality. It depends on $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}) and $\\NameCert_{\\RealUp}$ (\\autoref{ch:concrete-instances-real-namecert}), and is the immediate prerequisite for $\\NameCert_{\\BanachUp}$."),
    (68, "banach", "BanachUp",
     "The Banach-space interface $\\BanachUp$ packages a normed vector space carrier together with a regular Cauchy completeness witness in the metric induced by the norm. It depends on $\\NameCert_{\\NormUp}$ (\\autoref{ch:concrete-instances-norm-namecert}) and the real-completeness capstone (\\autoref{ch:capstones-real-completeness}), and supplies the substrate for $\\NameCert_{\\HilbertUp}$ and the operator certificates downstream."),
    (69, "hilbert", "HilbertUp",
     "The Hilbert-space interface $\\HilbertUp$ packages a Banach space whose norm is induced by an inner product. It depends on $\\NameCert_{\\InnerProductUp}$ (\\autoref{ch:concrete-instances-innerproduct-namecert}) and $\\NameCert_{\\BanachUp}$ (\\autoref{ch:concrete-instances-banach-namecert}), and is the substrate for the spectral and orthogonal-decomposition certificates of functional analysis."),
    (70, "measure", "MeasureUp",
     "The measure interface $\\MeasureUp$ packages a carrier with a constructive $\\sigma$-additive non-negative real-valued set function on a designated $\\sigma$-algebra of measurable subsets. It depends on $\\NameCert_{\\RealUp}$ (\\autoref{ch:concrete-instances-real-namecert}) and supplies the substrate for the integral certificate $\\NameCert_{\\IntegralUp}$ (\\autoref{ch:concrete-instances-integral-namecert})."),
    (71, "filter", "FilterUp",
     "The filter interface $\\FilterUp$ packages a non-empty upward-closed family of subsets of a carrier closed under finite intersections. It supplies the structural substrate for convergence and limit notions independent of metric data, and is the constructive analogue of mathlib-style \\texttt{Filter} for the BEDC topology and analysis layers."),
    (72, "functionalanalysis", "FunctionalAnalysisUp",
     "The functional-analysis interface $\\FunctionalAnalysisUp$ collects the bounded-linear-operator and dual-space certificates over $\\NameCert_{\\BanachUp}$ (\\autoref{ch:concrete-instances-banach-namecert}) and $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert}). It packages the operator norm, adjoints, and compactness witnesses required by the spectral, semigroup, and PDE certificates downstream."),
    (73, "completion", "CompletionUp",
     "The completion interface $\\CompletionUp$ packages the universal regular-Cauchy completion of a metric naming certificate. It depends on $\\NameCert_{\\MetricSpaceUp}$ (\\autoref{ch:concrete-instances-metric-namecert}) and the real-completeness capstone (\\autoref{ch:capstones-real-completeness}), generalising the $\\RatUp \\to \\RealUp$ construction to arbitrary located metric carriers."),
    (74, "manifold", "ManifoldUp",
     "The manifold interface $\\ManifoldUp$ packages a topological carrier with a finite atlas of charts into $(\\RealUp)^n$ whose transition maps are constructively smooth. It depends on $\\NameCert_{\\TopologyUp}$ (\\autoref{ch:concrete-instances-topology-namecert}) and the real-analytic certificate (\\autoref{ch:concrete-instances-real-analytic-namecert}), and supplies the substrate for the bundle and de~Rham certificates."),
    (75, "bundle", "BundleUp",
     "The bundle interface $\\BundleUp$ packages a fibred carrier $E \\to B$ with locally trivial fibres of a fixed model type. It depends on $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}) for the base and total-space topology, and supplies the substrate for the tangent, cotangent, and frame bundles."),
    (76, "homology", "HomologyUp",
     "The homology interface $\\HomologyUp$ packages a chain complex over an abelian-group carrier together with the kernel/image quotients computing the homology groups. It depends on $\\NameCert_{\\AbGroupUp}$ (\\autoref{ch:concrete-instances-abgroup-namecert}) and $\\NameCert_{\\QuotientGroupUp}$ (\\autoref{ch:concrete-instances-quotientgroup-namecert}), and is the constructive substrate for both singular and simplicial homology."),
    (77, "cohomology", "CohomologyUp",
     "The cohomology interface $\\CohomologyUp$ packages a cochain complex with the dual kernel/image quotients computing cohomology groups. It depends on $\\NameCert_{\\HomologyUp}$ (\\autoref{ch:concrete-instances-homology-namecert}) and supplies the structural substrate for de~Rham, sheaf, and \\v{C}ech cohomology certificates."),
    (78, "padic", "PadicUp",
     "The $p$-adic interface $\\PadicUp$ packages the carrier of regular Cauchy sequences over $\\NameCert_{\\RatUp}$ (\\autoref{ch:concrete-instances-rat-namecert}) under the $p$-adic absolute value, indexed by a prime $p$ from $\\NameCert_{\\PrimeUp}$ (\\autoref{ch:concrete-instances-prime-namecert}). It is the non-archimedean sibling of $\\NameCert_{\\RealUp}$ (\\autoref{ch:concrete-instances-real-namecert})."),
    (79, "adele", "AdeleUp",
     "The adele interface $\\AdeleUp$ packages the restricted product of $\\NameCert_{\\RealUp}$ and $\\NameCert_{\\PadicUp}$ over all primes $p$. It depends on $\\NameCert_{\\PadicUp}$ (\\autoref{ch:concrete-instances-padic-namecert}) and supplies the global object on which automorphic and L-function certificates are built."),
    (80, "modn", "ModNUp",
     "The modular-arithmetic interface $\\ModNUp$ packages the carrier of integers modulo a positive natural $n$. It depends on $\\NameCert_{\\IntUp}$ (\\autoref{ch:concrete-instances-int-namecert}) and is the canonical instance of $\\NameCert_{\\QuotientRingUp}$ (\\autoref{ch:concrete-instances-quotientring-namecert}) at the ideal $n\\mathbb{Z}$."),
    (81, "lfunction", "LFunctionUp",
     "The L-function interface $\\LFunctionUp$ packages a Dirichlet series whose coefficients arise from a fixed character or Galois representation, together with the analytic continuation and functional-equation witnesses. It depends on $\\NameCert_{\\DirichletSeriesUp}$ (\\autoref{ch:concrete-instances-dirichlet-series-namecert}) and is the abstract pattern instantiated by the Riemann zeta certificate $\\NameCert_{\\ZetaBasicUp}$ (\\autoref{ch:concrete-instances-zeta-basic-namecert})."),
    (82, "automorphic", "AutomorphicUp",
     "The automorphic-form interface $\\AutomorphicUp$ packages a function on $\\NameCert_{\\AdeleUp}$ (\\autoref{ch:concrete-instances-adele-namecert}) invariant under a discrete subgroup action and satisfying the constructive growth conditions. It supplies the substrate connecting representations of the adelic group to L-functions in the Langlands programme."),
    (83, "catlimit", "CatLimitUp",
     "The categorical-limit interface $\\CatLimitUp$ packages a cone over a diagram in a $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert}) certified universal among all such cones. It depends on $\\NameCert_{\\FunctorUp}$ (\\autoref{ch:concrete-instances-functor-namecert}) and is dual to $\\NameCert_{\\CatColimitUp}$ (\\autoref{ch:concrete-instances-catcolimit-namecert})."),
    (84, "catcolimit", "CatColimitUp",
     "The categorical-colimit interface $\\CatColimitUp$ packages a cocone over a diagram certified couniversal among all such cocones. It depends on $\\NameCert_{\\FunctorUp}$ (\\autoref{ch:concrete-instances-functor-namecert}) and is dual to $\\NameCert_{\\CatLimitUp}$ (\\autoref{ch:concrete-instances-catlimit-namecert})."),
    (85, "adjunction", "AdjunctionUp",
     "The adjunction interface $\\AdjunctionUp$ packages a pair of functors $F \\dashv G$ between two categories together with the natural-isomorphism witness on hom-sets. It depends on $\\NameCert_{\\FunctorUp}$ (\\autoref{ch:concrete-instances-functor-namecert}) and $\\NameCert_{\\NatTransUp}$ (\\autoref{ch:concrete-instances-nattrans-namecert}), and is the canonical structure underlying free/forgetful and Galois-style correspondences."),
    (86, "monad", "MonadUp",
     "The monad interface $\\MonadUp$ packages an endofunctor on a category with unit and multiplication natural transformations satisfying the monad laws. It depends on $\\NameCert_{\\NatTransUp}$ (\\autoref{ch:concrete-instances-nattrans-namecert}) and $\\NameCert_{\\AdjunctionUp}$ (\\autoref{ch:concrete-instances-adjunction-namecert}), and supplies the substrate for algebraic theories and computational effect models."),
    (87, "yoneda", "YonedaUp",
     "The Yoneda interface $\\YonedaUp$ packages, for each object of a category, the representable functor and the natural-isomorphism witness of the Yoneda lemma. It depends on $\\NameCert_{\\FunctorUp}$ (\\autoref{ch:concrete-instances-functor-namecert}) and $\\NameCert_{\\NatTransUp}$ (\\autoref{ch:concrete-instances-nattrans-namecert}), supplying the embedding into presheaf categories."),
    (88, "equivcat", "EquivCatUp",
     "The categorical-equivalence interface $\\EquivCatUp$ packages a pair of functors that are mutually quasi-inverse together with the natural-isomorphism witnesses. It depends on $\\NameCert_{\\AdjunctionUp}$ (\\autoref{ch:concrete-instances-adjunction-namecert}) and $\\NameCert_{\\NatTransUp}$ (\\autoref{ch:concrete-instances-nattrans-namecert}), and is the structural notion of sameness for $\\NameCert_{\\CategoryUp}$ instances."),
    (89, "set", "SetUp",
     "The set interface $\\SetUp$ packages a carrier together with a $\\psame$-classifier interpretable as set-membership equality. It is the type-layer counterpart of $\\NameCert_{\\PreorderUp}$ (\\autoref{ch:concrete-instances-preorder-namecert}) at the discrete level, and the substrate for $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert}) and $\\NameCert_{\\SubtypeUp}$ (\\autoref{ch:concrete-instances-subtype-namecert})."),
    (90, "finset", "FinSetUp",
     "The finite-set interface $\\FinSetUp$ packages a $\\NameCert_{\\SetUp}$ together with a finite enumeration witness via $\\NameCert_{\\ListUp}$ (\\autoref{ch:concrete-instances-list-namecert}). It depends on $\\NameCert_{\\SetUp}$ (\\autoref{ch:concrete-instances-set-namecert}) and is the substrate for combinatorial certificates such as $\\NameCert_{\\PermutationUp}$ and $\\NameCert_{\\GraphUp}$."),
    (91, "subtype", "SubtypeUp",
     "The subtype interface $\\SubtypeUp$ packages the carrier of elements of a parent $\\NameCert_{\\SetUp}$ satisfying a decidable predicate. It depends on $\\NameCert_{\\SetUp}$ (\\autoref{ch:concrete-instances-set-namecert}) and supplies the kernel-licit refinement type used throughout the algebra ladder for sub-objects."),
    (92, "empty", "EmptyUp",
     "The empty-type interface $\\EmptyUp$ packages the unique naming certificate over the inductive carrier with no constructors. It is the initial object in the category of naming certificates and supplies the canonical absurdity witness for refutation patterns."),
    (93, "unit", "UnitUp",
     "The unit-type interface $\\UnitUp$ packages the unique naming certificate over the inductive carrier with a single constructor. It is the terminal object in the category of naming certificates and supplies the canonical trivial witness for placeholder constructions."),
    (94, "permutation", "PermutationUp",
     "The permutation interface $\\PermutationUp$ packages the carrier of bijections of a $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert}) onto itself. It supplies the underlying carrier for $\\NameCert_{\\SymGroupUp}$ (\\autoref{ch:concrete-instances-symgroup-namecert}) and the action data for combinatorial group-theoretic certificates."),
    (95, "symgroup", "SymGroupUp",
     "The symmetric-group interface $\\SymGroupUp$ packages the group structure on $\\NameCert_{\\PermutationUp}$ (\\autoref{ch:concrete-instances-permutation-namecert}) under composition. It is a canonical instance of $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert}) and the substrate for representation-theoretic certificates."),
    (96, "graph", "GraphUp",
     "The graph interface $\\GraphUp$ packages a vertex carrier from $\\NameCert_{\\SetUp}$ (\\autoref{ch:concrete-instances-set-namecert}) together with a binary edge relation. It supplies the substrate for $\\NameCert_{\\TreeUp}$ (\\autoref{ch:concrete-instances-tree-namecert}) and for combinatorial structures such as posets viewed as DAGs."),
    (97, "tree", "TreeUp",
     "The tree interface $\\TreeUp$ packages a connected acyclic $\\NameCert_{\\GraphUp}$ (\\autoref{ch:concrete-instances-graph-namecert}) together with a designated root or root-free witness. It is the constructive substrate for inductive carriers and for the syntactic representation of derivations."),
    (98, "seq", "SeqUp",
     "The sequence interface $\\SeqUp$ packages a function $\\NatUp \\to A$ for a fixed naming-certificate carrier $A$, together with a regularity or boundedness modulus. It depends on $\\NameCert_{\\NatUp}$ (\\autoref{ch:concrete-instances-nat-namecert}) and is the general substrate for $\\NameCert_{\\SeriesUp}$, $\\NameCert_{\\ConvergenceRadiusUp}$, and the analytic-limit certificates."),
    (99, "series", "SeriesUp",
     "The series interface $\\SeriesUp$ packages the partial-sum sequence of a $\\NameCert_{\\SeqUp}$ (\\autoref{ch:concrete-instances-seq-namecert}) over an additive carrier together with explicit convergence moduli. It is the real-and-general counterpart of $\\NameCert_{\\ComplexSeriesUp}$ (\\autoref{ch:concrete-instances-complex-series-namecert})."),
    (100, "derivative", "DerivativeUp",
     "The derivative interface $\\DerivativeUp$ packages the constructive pointwise derivative of a function between metric carriers, with explicit modulus relating $\\varepsilon$ to the difference-quotient tolerance. It is the real and general counterpart of $\\NameCert_{\\ComplexDiffUp}$ (\\autoref{ch:concrete-instances-complex-diff-namecert})."),
    (101, "integral", "IntegralUp",
     "The integral interface $\\IntegralUp$ packages a measure-respecting integration operation on suitable function carriers over $\\NameCert_{\\MeasureUp}$ (\\autoref{ch:concrete-instances-measure-namecert}). It generalises the contour integral $\\NameCert_{\\ContourUp}$ (\\autoref{ch:concrete-instances-contour-integral}) to Riemann/Lebesgue settings on real and abstract carriers."),
    (102, "fourier", "FourierUp",
     "The Fourier interface $\\FourierUp$ packages the constructive Fourier series and transform of suitable functions on $\\NameCert_{\\SOneUp}$ (\\autoref{ch:concrete-instances-s1-namecert}) and $\\NameCert_{\\RealUp}$. It depends on $\\NameCert_{\\InnerProductUp}$ (\\autoref{ch:concrete-instances-innerproduct-namecert}) and $\\NameCert_{\\IntegralUp}$ (\\autoref{ch:concrete-instances-integral-namecert})."),
    (103, "residue", "ResidueUp",
     "The residue interface $\\ResidueUp$ packages the residue at an isolated singularity of a holomorphic function and the residue-theorem witness relating contour integrals to residue sums. It depends on $\\NameCert_{\\HolomorphicUp}$ (\\autoref{ch:concrete-instances-holomorphic-namecert}) and $\\NameCert_{\\ContourUp}$ (\\autoref{ch:concrete-instances-contour-integral})."),
    (104, "streamname", "StreamNameUp",
     "The stream-name interface $\\StreamNameUp$ packages an abstract sequential carrier underlying the Bishop-style L10 real-number construction. It is the lowest-level data on which $\\NameCert_{\\TotallyBoundedUp}$, $\\NameCert_{\\CompleteMetricUp}$, $\\NameCert_{\\CompactMetricUp}$, and $\\NameCert_{\\ContinuousMapUp}$ are built."),
    (105, "totallybounded", "TotallyBoundedUp",
     "The totally-bounded interface $\\TotallyBoundedUp$ packages a metric carrier admitting, for every $\\varepsilon > 0$, an explicit finite $\\varepsilon$-net. It depends on $\\NameCert_{\\MetricSpaceUp}$ (\\autoref{ch:concrete-instances-metric-namecert}) and is the prerequisite for $\\NameCert_{\\CompactMetricUp}$ (\\autoref{ch:concrete-instances-compactmetric-namecert})."),
    (106, "completemetric", "CompleteMetricUp",
     "The complete-metric interface $\\CompleteMetricUp$ packages a metric carrier in which every regular Cauchy sequence converges to an explicit limit with explicit modulus. It is the L10 sub-milestone certified by the real-completeness capstone (\\autoref{ch:capstones-real-completeness}) and the substrate for $\\NameCert_{\\BanachUp}$."),
    (107, "compactmetric", "CompactMetricUp",
     "The compact-metric interface $\\CompactMetricUp$ packages a metric carrier that is both totally bounded and complete in the senses of $\\NameCert_{\\TotallyBoundedUp}$ (\\autoref{ch:concrete-instances-totallybounded-namecert}) and $\\NameCert_{\\CompleteMetricUp}$ (\\autoref{ch:concrete-instances-completemetric-namecert}). It is the metric form of compactness used by the Heine--Cantor capstone (\\autoref{ch:capstones-compact-uniform-continuity})."),
    (108, "continuousmap", "ContinuousMapUp",
     "The continuous-map interface $\\ContinuousMapUp$ packages a function between metric carriers together with a pointwise modulus of continuity. It depends on $\\NameCert_{\\MetricSpaceUp}$ (\\autoref{ch:concrete-instances-metric-namecert}) and lifts $\\NameCert_{\\ContinuousFunctionUp}$ (\\autoref{ch:concrete-instances-continuous-namecert}) to general L10 metric carriers."),
    (109, "eqtype", "EqUp",
     "The equality-type interface $\\EqUp$ packages the constructive identity type over a carrier, with reflexivity as the sole constructor and explicit transport for kernel-licit substitution. It supplies the foundational equality layer underlying every $\\psame$ classifier."),
    (110, "funcobj", "FuncUp",
     "The function-object interface $\\FuncUp$ packages the carrier of functions $A \\to B$ between two naming certificates, together with the pointwise $\\hsame$-respecting structure. It supplies the substrate for $\\NameCert_{\\LinearMapUp}$ (\\autoref{ch:concrete-instances-linearmap-namecert}) and $\\NameCert_{\\ContinuousMapUp}$ (\\autoref{ch:concrete-instances-continuousmap-namecert}) as restrictions of the general function object."),
    (111, "riemannianmetric", "RiemannianMetricUp",
     "The Riemannian-metric interface $\\RiemannianMetricUp$ packages a smooth field of positive-definite inner products on the tangent fibres of a manifold carrier. It depends on $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}) and $\\NameCert_{\\InnerProductUp}$ (\\autoref{ch:concrete-instances-innerproduct-namecert}), and supplies the metric substrate for length, geodesic, and curvature certificates."),
    (112, "connection", "ConnectionUp",
     "The connection interface $\\ConnectionUp$ packages a covariant derivative on a fibre bundle, with linearity in the section argument and the Leibniz rule against scalar functions. It depends on $\\NameCert_{\\BundleUp}$ (\\autoref{ch:concrete-instances-bundle-namecert}) and $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}), and supplies the parallel-transport and curvature substrate."),
    (113, "curvature", "CurvatureUp",
     "The curvature interface $\\CurvatureUp$ packages the antisymmetric bracket of a connection, certifying the Bianchi identities and the tensorial behaviour under section change. It depends on $\\NameCert_{\\ConnectionUp}$ (\\autoref{ch:concrete-instances-connection-namecert}) and supplies the local invariants on which Riemannian and gauge-field certificates rest."),
    (114, "diffform", "DiffFormUp",
     "The differential-form interface $\\DiffFormUp$ packages the carrier of antisymmetric multilinear maps on the tangent bundle of a manifold, together with the wedge product. It depends on $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}) and $\\NameCert_{\\TensorProductUp}$ (\\autoref{ch:concrete-instances-tensorproduct-namecert}), and is the substrate for the de~Rham complex."),
    (115, "deRham", "DeRhamUp",
     "The de~Rham interface $\\DeRhamUp$ packages the exterior-derivative chain complex on differential forms, certifying $d^2 = 0$ and $\\hsame$-stability. It depends on $\\NameCert_{\\DiffFormUp}$ (\\autoref{ch:concrete-instances-diffform-namecert}) and $\\NameCert_{\\CohomologyUp}$ (\\autoref{ch:concrete-instances-cohomology-namecert}), and supplies the de~Rham cohomology of a manifold."),
    (116, "symplectic", "SymplecticUp",
     "The symplectic-structure interface $\\SymplecticUp$ packages a closed nondegenerate $2$-form on an even-dimensional manifold carrier. It depends on $\\NameCert_{\\DiffFormUp}$ (\\autoref{ch:concrete-instances-diffform-namecert}) and $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}), and is the substrate for Hamiltonian dynamics and Poisson-bracket certificates."),
    (117, "contact", "ContactUp",
     "The contact-structure interface $\\ContactUp$ packages a maximally nonintegrable hyperplane field on an odd-dimensional manifold carrier, recorded as a $1$-form whose top-degree wedge is nondegenerate. It depends on $\\NameCert_{\\DiffFormUp}$ (\\autoref{ch:concrete-instances-diffform-namecert}) and $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert})."),
    (118, "liegroup", "LieGroupUp",
     "The Lie-group interface $\\LieGroupUp$ packages a group carrier whose underlying set is a manifold and whose multiplication and inverse are constructively smooth. It depends on $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert}) and $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}), and is the substrate for representation, exponential, and root-system certificates."),
    (119, "liealgebra", "LieAlgebraUp",
     "The Lie-algebra interface $\\LieAlgebraUp$ packages a vector-space carrier endowed with an antisymmetric bilinear bracket satisfying the Jacobi identity. It depends on $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}), and is both the tangent-space-at-identity datum of a Lie group and the algebraic object on which root-system certificates are built."),
    (120, "expmap", "ExpMapUp",
     "The exponential-map interface $\\ExpMapUp$ packages the canonical map $\\mathfrak{g} \\to G$ from the Lie algebra to the Lie group of a connected Lie-group carrier. It depends on $\\NameCert_{\\LieGroupUp}$ (\\autoref{ch:concrete-instances-liegroup-namecert}) and $\\NameCert_{\\LieAlgebraUp}$ (\\autoref{ch:concrete-instances-liealgebra-namecert})."),
    (121, "adjointrep", "AdjointRepUp",
     "The adjoint-representation interface $\\AdjointRepUp$ packages the conjugation action $\\mathrm{Ad}\\colon G \\to \\mathrm{Aut}(\\mathfrak{g})$ together with its differential $\\mathrm{ad}$. It depends on $\\NameCert_{\\LieGroupUp}$ (\\autoref{ch:concrete-instances-liegroup-namecert}) and $\\NameCert_{\\LieAlgebraUp}$ (\\autoref{ch:concrete-instances-liealgebra-namecert})."),
    (122, "rootsystem", "RootSystemUp",
     "The root-system interface $\\RootSystemUp$ packages a finite set of nonzero vectors in a finite-dimensional inner-product space closed under the reflections they generate, with integer Cartan pairings. It depends on $\\NameCert_{\\InnerProductUp}$ (\\autoref{ch:concrete-instances-innerproduct-namecert}) and $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert}), and is the combinatorial backbone of semisimple Lie-algebra classification."),
    (123, "weylgroup", "WeylGroupUp",
     "The Weyl-group interface $\\WeylGroupUp$ packages the finite reflection group generated by the simple roots of a root system. It depends on $\\NameCert_{\\RootSystemUp}$ (\\autoref{ch:concrete-instances-rootsystem-namecert}) and $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert}), and is the discrete symmetry datum on which character-theoretic certificates rest."),
    (124, "bilinform", "BilinFormUp",
     "The bilinear-form interface $\\BilinFormUp$ packages a bilinear pairing on a module carrier together with its symmetry, antisymmetry, and nondegeneracy classifiers. It depends on $\\NameCert_{\\ModuleUp}$ (\\autoref{ch:concrete-instances-module-namecert}) and $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}), and is the universal datum from which inner products, symplectic forms, and Clifford algebras are licensed."),
    (125, "clifford", "CliffordUp",
     "The Clifford-algebra interface $\\CliffordUp$ packages the universal associative algebra generated by a vector-space carrier and a quadratic form $q$, modulo the relation $v \\cdot v = q(v)$. It depends on $\\NameCert_{\\TensorProductUp}$ (\\autoref{ch:concrete-instances-tensorproduct-namecert}) and $\\NameCert_{\\BilinFormUp}$ (\\autoref{ch:concrete-instances-bilinform-namecert}), and is the substrate for the Spin and Pin certificates."),
    (126, "spingroup", "SpinGroupUp",
     "The Spin-group interface $\\SpinGroupUp$ packages the connected double cover of the orthogonal group as a subgroup of the Clifford-algebra units. It depends on $\\NameCert_{\\CliffordUp}$ (\\autoref{ch:concrete-instances-clifford-namecert}) and $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert})."),
    (127, "pingroup", "PinGroupUp",
     "The Pin-group interface $\\PinGroupUp$ packages the double cover of the full orthogonal group, extending Spin by a reflection generator. It depends on $\\NameCert_{\\SpinGroupUp}$ (\\autoref{ch:concrete-instances-spingroup-namecert}) and $\\NameCert_{\\CliffordUp}$ (\\autoref{ch:concrete-instances-clifford-namecert})."),
    (128, "presheaf", "PreSheafUp",
     "The presheaf interface $\\PreSheafUp$ packages a contravariant functor from the open-sets category of a topological carrier to a target category, with restriction maps respecting composition and identity. It depends on $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert}) and $\\NameCert_{\\FunctorUp}$ (\\autoref{ch:concrete-instances-functor-namecert})."),
    (129, "sheaf", "SheafUp",
     "The sheaf interface $\\SheafUp$ packages a presheaf satisfying the locality and gluing axioms over open covers. It depends on $\\NameCert_{\\PreSheafUp}$ (\\autoref{ch:concrete-instances-presheaf-namecert}) and $\\NameCert_{\\TopologyUp}$ (\\autoref{ch:concrete-instances-topology-namecert}), and is the substrate for ringed-space and scheme certificates."),
    (130, "ringedspace", "RingedSpaceUp",
     "The ringed-space interface $\\RingedSpaceUp$ packages a topological carrier with a sheaf of commutative rings on it, certifying that stalks form local rings. It depends on $\\NameCert_{\\SheafUp}$ (\\autoref{ch:concrete-instances-sheaf-namecert}) and $\\NameCert_{\\CommRingUp}$ (\\autoref{ch:concrete-instances-commring-namecert})."),
    (131, "scheme", "SchemeUp",
     "The scheme interface $\\SchemeUp$ packages a locally ringed space that admits an open cover by spectra of commutative rings. It depends on $\\NameCert_{\\RingedSpaceUp}$ (\\autoref{ch:concrete-instances-ringedspace-namecert}) and $\\NameCert_{\\CommRingUp}$ (\\autoref{ch:concrete-instances-commring-namecert}), and is the substrate for affine and projective variety certificates."),
    (132, "affinevar", "AffineVarUp",
     "The affine-variety interface $\\AffineVarUp$ packages the zero-locus of a finite system of polynomial equations in the affine $n$-space of a commutative-ring carrier. It depends on $\\NameCert_{\\CommRingUp}$ (\\autoref{ch:concrete-instances-commring-namecert}) and $\\NameCert_{\\PolynomialUp}$ (\\autoref{ch:concrete-instances-polynomial-namecert})."),
    (133, "projectivevar", "ProjectiveVarUp",
     "The projective-variety interface $\\ProjectiveVarUp$ packages the zero-locus of a homogeneous polynomial ideal in the projective $n$-space of a commutative-ring carrier. It depends on $\\NameCert_{\\AffineVarUp}$ (\\autoref{ch:concrete-instances-affinevar-namecert}) and $\\NameCert_{\\PolynomialUp}$ (\\autoref{ch:concrete-instances-polynomial-namecert})."),
    (134, "homotopy", "HomotopyUp",
     "The homotopy interface $\\HomotopyUp$ packages the equivalence-of-paths relation between continuous maps under a continuous deformation parameter. It depends on $\\NameCert_{\\ContinuousMapUp}$ (\\autoref{ch:concrete-instances-continuousmap-namecert}) and $\\NameCert_{\\IntervalUp}$ (\\autoref{ch:concrete-instances-interval-namecert}), and is the substrate for fundamental-group and higher-homotopy certificates."),
    (135, "simplicialset", "SimplicialSetUp",
     "The simplicial-set interface $\\SimplicialSetUp$ packages a contravariant functor from the simplex category $\\Delta$ to a certified set carrier, with face and degeneracy operators satisfying the simplicial identities. It depends on $\\NameCert_{\\FunctorUp}$ (\\autoref{ch:concrete-instances-functor-namecert}) and $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert})."),
    (136, "modelcat", "ModelCatUp",
     "The model-category interface $\\ModelCatUp$ packages a category carrier with three distinguished classes of morphisms (cofibrations, fibrations, weak equivalences) satisfying lifting and factorisation axioms. It depends on $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert}), and is the homotopy-theoretic substrate beneath higher-category certificates."),
    (137, "infcat", "InfCatUp",
     "The $\\infty$-category interface $\\InfCatUp$ packages a simplicial-set carrier satisfying the inner-horn lifting condition (a quasicategory). It depends on $\\NameCert_{\\SimplicialSetUp}$ (\\autoref{ch:concrete-instances-simplicialset-namecert}) and $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert})."),
    (138, "derivedcat", "DerivedCatUp",
     "The derived-category interface $\\DerivedCatUp$ packages the localisation of a chain-complex category at quasi-isomorphisms. It depends on $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert}) and $\\NameCert_{\\CohomologyUp}$ (\\autoref{ch:concrete-instances-cohomology-namecert})."),
    (139, "fieldext", "FieldExtUp",
     "The field-extension interface $\\FieldExtUp$ packages an embedding of one field carrier into another, recording the larger field as a vector space over the smaller. It depends on $\\NameCert_{\\FieldUp}$ (\\autoref{ch:concrete-instances-field-namecert}) and $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}), and is the substrate for Galois, separable, and algebraic-closure certificates."),
    (140, "algclosure", "AlgClosureUp",
     "The algebraic-closure interface $\\AlgClosureUp$ packages a field extension in which every nonconstant polynomial over the base field has a root. It depends on $\\NameCert_{\\FieldExtUp}$ (\\autoref{ch:concrete-instances-fieldext-namecert}) and $\\NameCert_{\\PolynomialUp}$ (\\autoref{ch:concrete-instances-polynomial-namecert})."),
    (141, "galoisext", "GaloisExtUp",
     "The Galois-extension interface $\\GaloisExtUp$ packages a normal and separable field extension. It depends on $\\NameCert_{\\FieldExtUp}$ (\\autoref{ch:concrete-instances-fieldext-namecert}) and $\\NameCert_{\\SeparableExtUp}$ (\\autoref{ch:concrete-instances-separableext-namecert})."),
    (142, "galoisgroup", "GaloisGroupUp",
     "The Galois-group interface $\\GaloisGroupUp$ packages the group of field automorphisms of a Galois extension fixing the base field pointwise. It depends on $\\NameCert_{\\GaloisExtUp}$ (\\autoref{ch:concrete-instances-galoisext-namecert}) and $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert})."),
    (143, "splittingfield", "SplittingFieldUp",
     "The splitting-field interface $\\SplittingFieldUp$ packages the smallest field extension over which a given polynomial factors into linear terms. It depends on $\\NameCert_{\\FieldExtUp}$ (\\autoref{ch:concrete-instances-fieldext-namecert}) and $\\NameCert_{\\PolynomialUp}$ (\\autoref{ch:concrete-instances-polynomial-namecert})."),
    (144, "separableext", "SeparableExtUp",
     "The separable-extension interface $\\SeparableExtUp$ packages a field extension whose minimal polynomials all have simple roots. It depends on $\\NameCert_{\\FieldExtUp}$ (\\autoref{ch:concrete-instances-fieldext-namecert}) and $\\NameCert_{\\PolynomialUp}$ (\\autoref{ch:concrete-instances-polynomial-namecert})."),
    (145, "transcendence", "TranscendenceUp",
     "The transcendence interface $\\TranscendenceUp$ packages the supremum of cardinalities of algebraically independent subsets of a field extension. It depends on $\\NameCert_{\\FieldExtUp}$ (\\autoref{ch:concrete-instances-fieldext-namecert})."),
    (146, "numfield", "NumFieldUp",
     "The number-field interface $\\NumFieldUp$ packages a finite field extension of the rational-number certificate. It depends on $\\NameCert_{\\FieldExtUp}$ (\\autoref{ch:concrete-instances-fieldext-namecert}) and $\\NameCert_{\\RatUp}$ (\\autoref{ch:concrete-instances-rat-namecert})."),
    (147, "ringofintegers", "RingOfIntegersUp",
     "The ring-of-integers interface $\\RingOfIntegersUp$ packages the integral closure of $\\IntUp$ inside a number-field carrier. It depends on $\\NameCert_{\\NumFieldUp}$ (\\autoref{ch:concrete-instances-numfield-namecert}) and $\\NameCert_{\\IntUp}$ (\\autoref{ch:concrete-instances-int-namecert})."),
    (148, "idealclass", "IdealClassUp",
     "The ideal-class interface $\\IdealClassUp$ packages the quotient group of fractional ideals modulo principal ideals in a Dedekind domain. It depends on $\\NameCert_{\\DedekindUp}$ (\\autoref{ch:concrete-instances-dedekind-namecert}) and $\\NameCert_{\\QuotientGroupUp}$ (\\autoref{ch:concrete-instances-quotientgroup-namecert})."),
    (149, "dirichletunit", "DirichletUnitUp",
     "The Dirichlet-unit interface $\\DirichletUnitUp$ packages the structure of the unit group of a ring of integers as a finitely generated abelian group of rank $r_1 + r_2 - 1$. It depends on $\\NameCert_{\\RingOfIntegersUp}$ (\\autoref{ch:concrete-instances-ringofintegers-namecert}) and $\\NameCert_{\\AbGroupUp}$ (\\autoref{ch:concrete-instances-abgroup-namecert})."),
    (150, "dedekind", "DedekindUp",
     "The Dedekind-domain interface $\\DedekindUp$ packages an integrally closed Noetherian commutative domain in which every nonzero prime ideal is maximal. It depends on $\\NameCert_{\\CommRingUp}$ (\\autoref{ch:concrete-instances-commring-namecert}) and $\\NameCert_{\\IdealUp}$ (\\autoref{ch:concrete-instances-ideal-namecert})."),
    (151, "localfield", "LocalFieldUp",
     "The local-field interface $\\LocalFieldUp$ packages a complete discretely valued field with finite residue field. It depends on $\\NameCert_{\\FieldUp}$ (\\autoref{ch:concrete-instances-field-namecert}) and $\\NameCert_{\\PadicUp}$ (\\autoref{ch:concrete-instances-padic-namecert})."),
    (152, "cyclotomic", "CyclotomicUp",
     "The cyclotomic-field interface $\\CyclotomicUp$ packages the splitting field of $X^n - 1$ over the rational-number certificate. It depends on $\\NameCert_{\\NumFieldUp}$ (\\autoref{ch:concrete-instances-numfield-namecert}) and $\\NameCert_{\\SplittingFieldUp}$ (\\autoref{ch:concrete-instances-splittingfield-namecert})."),
    (153, "ellipticcurve", "EllipticCurveUp",
     "The elliptic-curve interface $\\EllipticCurveUp$ packages a smooth projective genus-one curve over a field carrier together with a chosen base point. It depends on $\\NameCert_{\\ProjectiveVarUp}$ (\\autoref{ch:concrete-instances-projectivevar-namecert}) and $\\NameCert_{\\FieldUp}$ (\\autoref{ch:concrete-instances-field-namecert})."),
    (154, "abeliancat", "AbelianCatUp",
     "The abelian-category interface $\\AbelianCatUp$ packages an additive category in which every morphism has a kernel and cokernel and the canonical epi-mono factorisation is an isomorphism. It depends on $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert}) and $\\NameCert_{\\AbGroupUp}$ (\\autoref{ch:concrete-instances-abgroup-namecert})."),
    (155, "derivedfunctor", "DerivedFunctorUp",
     "The derived-functor interface $\\DerivedFunctorUp$ packages the right- or left-derived $R^iF$ / $L_iF$ of an additive functor between abelian categories. It depends on $\\NameCert_{\\AbelianCatUp}$ (\\autoref{ch:concrete-instances-abeliancat-namecert}) and $\\NameCert_{\\HomologyUp}$ (\\autoref{ch:concrete-instances-homology-namecert})."),
    (156, "spectralseq", "SpectralSeqUp",
     "The spectral-sequence interface $\\SpectralSeqUp$ packages a sequence of bigraded objects with differentials whose successive cohomologies converge to a target. It depends on $\\NameCert_{\\HomologyUp}$ (\\autoref{ch:concrete-instances-homology-namecert}) and $\\NameCert_{\\AbelianCatUp}$ (\\autoref{ch:concrete-instances-abeliancat-namecert})."),
    (157, "triangulatedcat", "TriangulatedCatUp",
     "The triangulated-category interface $\\TriangulatedCatUp$ packages an additive category with a translation autoequivalence and a class of distinguished triangles satisfying the octahedral axiom. It depends on $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert}) and $\\NameCert_{\\DerivedCatUp}$ (\\autoref{ch:concrete-instances-derivedcat-namecert})."),
    (158, "hopfalg", "HopfAlgUp",
     "The Hopf-algebra interface $\\HopfAlgUp$ packages a bialgebra carrier together with an antipode satisfying the convolution-inverse axiom. It depends on $\\NameCert_{\\RingUp}$ (\\autoref{ch:concrete-instances-ring-namecert}) and $\\NameCert_{\\TensorProductUp}$ (\\autoref{ch:concrete-instances-tensorproduct-namecert})."),
    (159, "monoidalcat", "MonoidalCatUp",
     "The monoidal-category interface $\\MonoidalCatUp$ packages a category with a tensor-product bifunctor, unit object, and coherent associator and unitor isomorphisms. It depends on $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert})."),
    (160, "enrichedcat", "EnrichedCatUp",
     "The enriched-category interface $\\EnrichedCatUp$ packages a collection of objects with hom-objects valued in a fixed monoidal category, with composition and identity morphisms in that monoidal category. It depends on $\\NameCert_{\\MonoidalCatUp}$ (\\autoref{ch:concrete-instances-monoidalcat-namecert}) and $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert})."),
    (161, "topos", "ToposUp",
     "The topos interface $\\ToposUp$ packages a category with finite limits, exponentials, and a subobject classifier. It depends on $\\NameCert_{\\CategoryUp}$ (\\autoref{ch:concrete-instances-category-namecert}) and $\\NameCert_{\\SheafUp}$ (\\autoref{ch:concrete-instances-sheaf-namecert}), and is the substrate for sheaf-of-sets cohomology and internal logic."),
    (162, "probspace", "ProbSpaceUp",
     "The probability-space interface $\\ProbSpaceUp$ packages a measure space whose total measure is the unit. It depends on $\\NameCert_{\\MeasureUp}$ (\\autoref{ch:concrete-instances-measure-namecert}) and $\\NameCert_{\\RealUp}$ (\\autoref{ch:concrete-instances-real-namecert})."),
    (163, "randomvar", "RandomVarUp",
     "The random-variable interface $\\RandomVarUp$ packages a measurable function from a probability space to a target measure space. It depends on $\\NameCert_{\\ProbSpaceUp}$ (\\autoref{ch:concrete-instances-probspace-namecert}) and $\\NameCert_{\\MeasureUp}$ (\\autoref{ch:concrete-instances-measure-namecert})."),
    (164, "distribution", "DistributionUp",
     "The distribution interface $\\DistributionUp$ packages the pushforward measure of a random variable on its target space. It depends on $\\NameCert_{\\RandomVarUp}$ (\\autoref{ch:concrete-instances-randomvar-namecert}) and $\\NameCert_{\\MeasureUp}$ (\\autoref{ch:concrete-instances-measure-namecert})."),
    (165, "independence", "IndependenceUp",
     "The independence interface $\\IndependenceUp$ packages the property that the joint distribution of a finite family of random variables factors as the product of marginals. It depends on $\\NameCert_{\\RandomVarUp}$ (\\autoref{ch:concrete-instances-randomvar-namecert}) and $\\NameCert_{\\DistributionUp}$ (\\autoref{ch:concrete-instances-distribution-namecert})."),
    (166, "condexp", "CondExpUp",
     "The conditional-expectation interface $\\CondExpUp$ packages the $L^2$ projection of an integrable random variable onto the subspace of functions measurable with respect to a sub-$\\sigma$-algebra. It depends on $\\NameCert_{\\RandomVarUp}$ (\\autoref{ch:concrete-instances-randomvar-namecert}) and $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert})."),
    (167, "markovchain", "MarkovChainUp",
     "The Markov-chain interface $\\MarkovChainUp$ packages a sequence of random variables in which the conditional distribution of each step depends only on the previous step. It depends on $\\NameCert_{\\RandomVarUp}$ (\\autoref{ch:concrete-instances-randomvar-namecert}) and $\\NameCert_{\\DistributionUp}$ (\\autoref{ch:concrete-instances-distribution-namecert})."),
    (168, "martingale", "MartingaleUp",
     "The martingale interface $\\MartingaleUp$ packages an adapted sequence of integrable random variables whose conditional expectation at each step is the previous value. It depends on $\\NameCert_{\\RandomVarUp}$ (\\autoref{ch:concrete-instances-randomvar-namecert}) and $\\NameCert_{\\CondExpUp}$ (\\autoref{ch:concrete-instances-condexp-namecert})."),
    (169, "brownian", "BrownianUp",
     "The Brownian-motion interface $\\BrownianUp$ packages a continuous-time stochastic process with independent normally distributed increments and continuous sample paths. It depends on $\\NameCert_{\\MartingaleUp}$ (\\autoref{ch:concrete-instances-martingale-namecert}) and $\\NameCert_{\\ContinuousMapUp}$ (\\autoref{ch:concrete-instances-continuousmap-namecert})."),
    (170, "entropy", "EntropyUp",
     "The entropy interface $\\EntropyUp$ packages the Shannon entropy $-\\sum p_i \\log p_i$ of a discrete distribution and the differential entropy $-\\int f \\log f$ of a continuous one. It depends on $\\NameCert_{\\DistributionUp}$ (\\autoref{ch:concrete-instances-distribution-namecert}) and $\\NameCert_{\\IntegralUp}$ (\\autoref{ch:concrete-instances-integral-namecert})."),
    (171, "ode", "OdeUp",
     "The ordinary-differential-equation interface $\\OdeUp$ packages a system $\\dot x = F(t, x)$ together with the local existence and uniqueness data on Lipschitz vector fields. It depends on $\\NameCert_{\\DerivativeUp}$ (\\autoref{ch:concrete-instances-derivative-namecert}) and $\\NameCert_{\\BanachUp}$ (\\autoref{ch:concrete-instances-banach-namecert})."),
    (172, "pde", "PdeUp",
     "The partial-differential-equation interface $\\PdeUp$ packages a relation among partial derivatives of a function on a manifold carrier together with classification by order, type, and boundary data. It depends on $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}) and $\\NameCert_{\\DerivativeUp}$ (\\autoref{ch:concrete-instances-derivative-namecert})."),
    (173, "dynsystem", "DynSystemUp",
     "The dynamical-system interface $\\DynSystemUp$ packages a one-parameter family of self-maps of a phase-space carrier satisfying the flow axioms. It depends on $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}) and $\\NameCert_{\\OdeUp}$ (\\autoref{ch:concrete-instances-ode-namecert})."),
    (174, "ergodic", "ErgodicUp",
     "The ergodic-theory interface $\\ErgodicUp$ packages a measure-preserving transformation together with the ergodic decomposition of its invariant subspaces. It depends on $\\NameCert_{\\DynSystemUp}$ (\\autoref{ch:concrete-instances-dynsystem-namecert}) and $\\NameCert_{\\MeasureUp}$ (\\autoref{ch:concrete-instances-measure-namecert})."),
    (175, "firstorder", "FirstOrderUp",
     "The first-order-logic interface $\\FirstOrderUp$ packages a signature of relation and function symbols, a set of formulas, and a deduction calculus together with the soundness and completeness data. It depends on $\\NameCert_{\\SetUp}$ (\\autoref{ch:concrete-instances-set-namecert}) and $\\NameCert_{\\TreeUp}$ (\\autoref{ch:concrete-instances-tree-namecert})."),
    (176, "modeltheory", "ModelTheoryUp",
     "The model-theory interface $\\ModelTheoryUp$ packages a structure for a first-order signature, satisfaction of formulas, elementary equivalence, and elementary substructures. It depends on $\\NameCert_{\\FirstOrderUp}$ (\\autoref{ch:concrete-instances-firstorder-namecert})."),
    (177, "computable", "ComputableUp",
     "The computable-function interface $\\ComputableUp$ packages partial functions $\\mathbb{N} \\to \\mathbb{N}$ defined by Turing-machine simulation up to time-step bounds. It depends on $\\NameCert_{\\NatUp}$ (\\autoref{ch:concrete-instances-nat-namecert}) and $\\NameCert_{\\SeqUp}$ (\\autoref{ch:concrete-instances-seq-namecert})."),
    (178, "lambdacalc", "LambdaCalcUp",
     "The lambda-calculus interface $\\LambdaCalcUp$ packages the inductive carrier of $\\lambda$-terms together with $\\beta$-reduction, $\\alpha$-equivalence, and a stability classifier under capture-avoiding substitution. It depends on $\\NameCert_{\\TreeUp}$ (\\autoref{ch:concrete-instances-tree-namecert}) and $\\NameCert_{\\NatUp}$ (\\autoref{ch:concrete-instances-nat-namecert})."),
    (179, "partition", "PartitionUp",
     "The integer-partition interface $\\PartitionUp$ packages weakly decreasing sequences of positive integers summing to a fixed integer, together with the Young-diagram interpretation. It depends on $\\NameCert_{\\NatUp}$ (\\autoref{ch:concrete-instances-nat-namecert}) and $\\NameCert_{\\ListUp}$ (\\autoref{ch:concrete-instances-list-namecert})."),
    (180, "matroid", "MatroidUp",
     "The matroid interface $\\MatroidUp$ packages a finite ground set with a family of subsets (independent sets) closed under taking subsets and satisfying the exchange axiom. It depends on $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert}) and $\\NameCert_{\\LatticeUp}$ (\\autoref{ch:concrete-instances-lattice-namecert})."),
    (181, "ramsey", "RamseyUp",
     "The Ramsey-theory interface $\\RamseyUp$ packages, for every finite colouring of the $r$-element subsets of a sufficiently large finite set, a monochromatic subset of bounded size. It depends on $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert}) and $\\NameCert_{\\GraphUp}$ (\\autoref{ch:concrete-instances-graph-namecert})."),
    (182, "topgroup", "TopGroupUp",
     "The topological-group interface $\\TopGroupUp$ packages a group carrier with a topology making multiplication and inversion continuous. It depends on $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert}) and $\\NameCert_{\\TopologyUp}$ (\\autoref{ch:concrete-instances-topology-namecert})."),
    (183, "topvecspace", "TopVecSpaceUp",
     "The topological-vector-space interface $\\TopVecSpaceUp$ packages a vector-space carrier with a Hausdorff topology making addition and scalar multiplication continuous. It depends on $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}) and $\\NameCert_{\\TopologyUp}$ (\\autoref{ch:concrete-instances-topology-namecert})."),
    (184, "affinespace", "AffineSpaceUp",
     "The affine-space interface $\\AffineSpaceUp$ packages a torsor over a vector-space carrier: a set with a free transitive action of vector translations. It depends on $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}) and $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert})."),
    (185, "projectivespace", "ProjectiveSpaceUp",
     "The projective-space interface $\\ProjectiveSpaceUp$ packages the quotient of a punctured vector-space carrier by the scaling action of the underlying field's multiplicative group. It depends on $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}) and $\\NameCert_{\\FieldUp}$ (\\autoref{ch:concrete-instances-field-namecert})."),
    (186, "convexset", "ConvexSetUp",
     "The convex-set interface $\\ConvexSetUp$ packages a subset of a vector-space carrier closed under affine combinations with nonnegative coefficients summing to one. It depends on $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert}) and $\\NameCert_{\\AffineSpaceUp}$ (\\autoref{ch:concrete-instances-affinespace-namecert})."),
    (187, "polytope", "PolytopeUp",
     "The polytope interface $\\PolytopeUp$ packages a bounded convex set in a finite-dimensional vector-space carrier presented as the intersection of finitely many half-spaces, with vertex, edge, and face combinatorial structure. It depends on $\\NameCert_{\\ConvexSetUp}$ (\\autoref{ch:concrete-instances-convexset-namecert}) and $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert})."),
    (188, "vectorbundle", "VectorBundleUp",
     "The vector-bundle interface $\\VectorBundleUp$ packages a fibre bundle whose fibres are vector spaces and whose transition maps are linear. It depends on $\\NameCert_{\\BundleUp}$ (\\autoref{ch:concrete-instances-bundle-namecert}) and $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert})."),
    (189, "cstaralgebra", "CStarAlgUp",
     "The C*-algebra interface $\\CStarAlgUp$ packages a Banach algebra with an involution satisfying $\\|a^* a\\| = \\|a\\|^2$. It depends on $\\NameCert_{\\BanachUp}$ (\\autoref{ch:concrete-instances-banach-namecert}) and $\\NameCert_{\\RingUp}$ (\\autoref{ch:concrete-instances-ring-namecert}), and is the substrate for noncommutative topology and operator-theoretic spectra."),
    (190, "vonneumannalgebra", "VonNeumannAlgUp",
     "The von Neumann algebra interface $\\VonNeumannAlgUp$ packages a unital $*$-subalgebra of $B(H)$ closed in the weak operator topology. It depends on $\\NameCert_{\\CStarAlgUp}$ (\\autoref{ch:concrete-instances-cstaralgebra-namecert}) and $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert})."),
    (191, "operatorideal", "OperatorIdealUp",
     "The operator-ideal interface $\\OperatorIdealUp$ packages a two-sided ideal of bounded operators on a Hilbert space carrier (compact, trace class, Hilbert-Schmidt). It depends on $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert}) and $\\NameCert_{\\IdealUp}$ (\\autoref{ch:concrete-instances-ideal-namecert})."),
    (192, "spectraltheorem", "SpectralTheoremUp",
     "The spectral-theorem interface $\\SpectralTheoremUp$ packages the diagonalisation data of a self-adjoint or normal bounded operator: spectrum, projection-valued measure, and functional calculus. It depends on $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert}) and $\\NameCert_{\\MeasureUp}$ (\\autoref{ch:concrete-instances-measure-namecert})."),
    (193, "nuclear", "NuclearUp",
     "The nuclear-operator interface $\\NuclearUp$ packages compact operators between Banach spaces representable as absolutely convergent rank-one sums. It depends on $\\NameCert_{\\BanachUp}$ (\\autoref{ch:concrete-instances-banach-namecert}) and $\\NameCert_{\\OperatorIdealUp}$ (\\autoref{ch:concrete-instances-operatorideal-namecert})."),
    (194, "factor", "FactorUp",
     "The factor interface $\\FactorUp$ packages a von Neumann algebra with trivial centre, classified into types $\\mathrm{I}$, $\\mathrm{II}_1$, $\\mathrm{II}_\\infty$, $\\mathrm{III}$. It depends on $\\NameCert_{\\VonNeumannAlgUp}$ (\\autoref{ch:concrete-instances-vonneumannalgebra-namecert})."),
    (195, "quantumstate", "QuantumStateUp",
     "The quantum-state interface $\\QuantumStateUp$ packages a unit vector in a Hilbert space carrier together with the equivalence under global phase. It depends on $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert}) and $\\NameCert_{\\ProjectiveSpaceUp}$ (\\autoref{ch:concrete-instances-projectivespace-namecert})."),
    (196, "observable", "ObservableUp",
     "The observable interface $\\ObservableUp$ packages a self-adjoint operator on a Hilbert space carrier together with its spectrum and expectation pairing with quantum states. It depends on $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert}) and $\\NameCert_{\\SpectralTheoremUp}$ (\\autoref{ch:concrete-instances-spectraltheorem-namecert})."),
    (197, "unitarygroup", "UnitaryGroupUp",
     "The unitary-group interface $\\UnitaryGroupUp$ packages the Lie group of inner-product-preserving automorphisms of a Hilbert space carrier. It depends on $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert}) and $\\NameCert_{\\LieGroupUp}$ (\\autoref{ch:concrete-instances-liegroup-namecert})."),
    (198, "densitymatrix", "DensityMatrixUp",
     "The density-matrix interface $\\DensityMatrixUp$ packages a positive trace-class operator of trace one on a Hilbert space carrier (a mixed quantum state). It depends on $\\NameCert_{\\OperatorIdealUp}$ (\\autoref{ch:concrete-instances-operatorideal-namecert}) and $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert})."),
    (199, "quantumchannel", "QuantumChannelUp",
     "The quantum-channel interface $\\QuantumChannelUp$ packages a completely positive trace-preserving (CPTP) linear map between density-matrix spaces. It depends on $\\NameCert_{\\DensityMatrixUp}$ (\\autoref{ch:concrete-instances-densitymatrix-namecert}) and $\\NameCert_{\\LinearMapUp}$ (\\autoref{ch:concrete-instances-linearmap-namecert})."),
    (200, "entanglement", "EntanglementUp",
     "The entanglement interface $\\EntanglementUp$ packages the structure obstruction of a bipartite quantum state to factor as a tensor product of pure states, certified via Schmidt rank or entanglement entropy. It depends on $\\NameCert_{\\QuantumStateUp}$ (\\autoref{ch:concrete-instances-quantumstate-namecert}) and $\\NameCert_{\\TensorProductUp}$ (\\autoref{ch:concrete-instances-tensorproduct-namecert})."),
    (201, "newtoniteration", "NewtonIterationUp",
     "The Newton-iteration interface $\\NewtonIterationUp$ packages the iterative scheme $x_{n+1} = x_n - F(x_n)/F'(x_n)$ for finding zeros of a differentiable map, with quadratic convergence on a contraction neighbourhood. It depends on $\\NameCert_{\\DerivativeUp}$ (\\autoref{ch:concrete-instances-derivative-namecert}) and $\\NameCert_{\\BanachUp}$ (\\autoref{ch:concrete-instances-banach-namecert})."),
    (202, "interpolation", "InterpolationUp",
     "The polynomial-interpolation interface $\\InterpolationUp$ packages, for a finite set of distinct points and target values, the unique polynomial of degree below the count that hits each target. It depends on $\\NameCert_{\\PolynomialUp}$ (\\autoref{ch:concrete-instances-polynomial-namecert}) and $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert})."),
    (203, "approximation", "ApproximationUp",
     "The best-approximation interface $\\ApproximationUp$ packages, for a continuous function on a compact carrier, the polynomial of bounded degree minimising the supremum-norm error (Weierstrass / Chebyshev). It depends on $\\NameCert_{\\ContinuousMapUp}$ (\\autoref{ch:concrete-instances-continuousmap-namecert}) and $\\NameCert_{\\PolynomialUp}$ (\\autoref{ch:concrete-instances-polynomial-namecert})."),
    (204, "fft", "FftUp",
     "The Fast-Fourier-transform interface $\\FftUp$ packages the $O(n \\log n)$ divide-and-conquer evaluation of the discrete Fourier transform on length-$n$ data when $n$ has small prime factors. It depends on $\\NameCert_{\\FourierUp}$ (\\autoref{ch:concrete-instances-fourier-namecert}) and $\\NameCert_{\\ComplexUp}$ (\\autoref{ch:concrete-instances-complex-namecert})."),
    (205, "quadrature", "QuadratureUp",
     "The numerical-quadrature interface $\\QuadratureUp$ packages a finite weighted sum approximating an integral on a compact interval, classified by exactness degree (trapezoid, Simpson, Gauss-Legendre). It depends on $\\NameCert_{\\IntegralUp}$ (\\autoref{ch:concrete-instances-integral-namecert}) and $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert})."),
    (206, "fisherinfo", "FisherInfoUp",
     "The Fisher-information interface $\\FisherInfoUp$ packages, for a parametric family of distributions, the Riemannian metric whose components are expectations of squared score functions. It depends on $\\NameCert_{\\DistributionUp}$ (\\autoref{ch:concrete-instances-distribution-namecert}) and $\\NameCert_{\\RiemannianMetricUp}$ (\\autoref{ch:concrete-instances-riemannianmetric-namecert})."),
    (207, "statmanifold", "StatManifoldUp",
     "The statistical-manifold interface $\\StatManifoldUp$ packages a parameter-space manifold whose points label probability distributions, equipped with the Fisher information metric and dual affine connections. It depends on $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}) and $\\NameCert_{\\FisherInfoUp}$ (\\autoref{ch:concrete-instances-fisherinfo-namecert})."),
    (208, "estimator", "EstimatorUp",
     "The estimator interface $\\EstimatorUp$ packages a sequence of measurable functions of i.i.d. samples taking values in a parameter space, with consistency, bias, and variance certificates. It depends on $\\NameCert_{\\RandomVarUp}$ (\\autoref{ch:concrete-instances-randomvar-namecert}) and $\\NameCert_{\\IndependenceUp}$ (\\autoref{ch:concrete-instances-independence-namecert})."),
    (209, "hypothesis", "HypothesisTestUp",
     "The hypothesis-testing interface $\\HypothesisTestUp$ packages a decision procedure between null and alternative distributional hypotheses certified by Type I and Type II error bounds. It depends on $\\NameCert_{\\DistributionUp}$ (\\autoref{ch:concrete-instances-distribution-namecert}) and $\\NameCert_{\\ProbSpaceUp}$ (\\autoref{ch:concrete-instances-probspace-namecert})."),
    (210, "bayesian", "BayesianUp",
     "The Bayesian-update interface $\\BayesianUp$ packages the conditional-probability rule transforming a prior distribution and likelihood into a posterior distribution. It depends on $\\NameCert_{\\DistributionUp}$ (\\autoref{ch:concrete-instances-distribution-namecert}) and $\\NameCert_{\\CondExpUp}$ (\\autoref{ch:concrete-instances-condexp-namecert})."),
    (211, "networkflow", "NetworkFlowUp",
     "The network-flow interface $\\NetworkFlowUp$ packages a directed graph carrier with edge capacities together with the maximum-flow / minimum-cut duality. It depends on $\\NameCert_{\\GraphUp}$ (\\autoref{ch:concrete-instances-graph-namecert}) and $\\NameCert_{\\NatUp}$ (\\autoref{ch:concrete-instances-nat-namecert})."),
    (212, "matching", "MatchingUp",
     "The graph-matching interface $\\MatchingUp$ packages a subset of edges in a graph carrier with no shared vertex, together with the maximum-matching / minimum-vertex-cover duality on bipartite graphs. It depends on $\\NameCert_{\\GraphUp}$ (\\autoref{ch:concrete-instances-graph-namecert}) and $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert})."),
    (213, "lpduality", "LPDualityUp",
     "The linear-programming-duality interface $\\LPDualityUp$ packages a primal/dual pair of linear programs together with strong-duality and complementary-slackness certificates over an ordered field. It depends on $\\NameCert_{\\ConvexSetUp}$ (\\autoref{ch:concrete-instances-convexset-namecert}) and $\\NameCert_{\\PolytopeUp}$ (\\autoref{ch:concrete-instances-polytope-namecert})."),
    (214, "shortestpath", "ShortestPathUp",
     "The shortest-path interface $\\ShortestPathUp$ packages, on a weighted graph carrier with nonnegative weights, the path of minimum total weight between two vertices together with Dijkstra and Bellman-Ford correctness certificates. It depends on $\\NameCert_{\\GraphUp}$ (\\autoref{ch:concrete-instances-graph-namecert}) and $\\NameCert_{\\RealUp}$ (\\autoref{ch:concrete-instances-real-namecert})."),
    (215, "spanningtree", "SpanningTreeUp",
     "The spanning-tree interface $\\SpanningTreeUp$ packages a maximal acyclic subgraph reaching every vertex of a connected graph carrier, with minimum-weight selection in the weighted case (Kruskal / Prim). It depends on $\\NameCert_{\\GraphUp}$ (\\autoref{ch:concrete-instances-graph-namecert}) and $\\NameCert_{\\TreeUp}$ (\\autoref{ch:concrete-instances-tree-namecert})."),
    (216, "simplicialcomplex", "SimplicialComplexUp",
     "The simplicial-complex interface $\\SimplicialComplexUp$ packages a finite collection of simplices closed under taking faces, with face-incidence and dimension-grading data. It depends on $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert}) and $\\NameCert_{\\PosetUp}$ (\\autoref{ch:concrete-instances-poset-namecert})."),
    (217, "persistenthom", "PersistentHomUp",
     "The persistent-homology interface $\\PersistentHomUp$ packages the bigraded module of homology groups of a filtered simplicial complex together with the persistence-diagram / barcode summary. It depends on $\\NameCert_{\\HomologyUp}$ (\\autoref{ch:concrete-instances-homology-namecert}) and $\\NameCert_{\\SimplicialComplexUp}$ (\\autoref{ch:concrete-instances-simplicialcomplex-namecert})."),
    (218, "mapper", "MapperUp",
     "The Mapper interface $\\MapperUp$ packages, for a continuous function from a topological space to a parameter range, the simplicial-complex skeleton built from clusterings of preimages of a finite cover. It depends on $\\NameCert_{\\SimplicialComplexUp}$ (\\autoref{ch:concrete-instances-simplicialcomplex-namecert}) and $\\NameCert_{\\TopologyUp}$ (\\autoref{ch:concrete-instances-topology-namecert})."),
    (219, "errorcode", "ErrorCodeUp",
     "The error-correcting-code interface $\\ErrorCodeUp$ packages a subset of $\\mathbb{F}_q^n$ at minimum Hamming distance $d$ together with encoder, syndrome, and decoder data correcting up to $\\lfloor (d-1)/2 \\rfloor$ errors. It depends on $\\NameCert_{\\FieldUp}$ (\\autoref{ch:concrete-instances-field-namecert}) and $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert})."),
    (220, "hash", "HashUp",
     "The hash-function interface $\\HashUp$ packages a deterministic finite-output map with collision-resistance, preimage-resistance, and second-preimage-resistance certificates against a bounded adversary. It depends on $\\NameCert_{\\FuncUp}$ (\\autoref{ch:concrete-instances-funcobj-namecert}) and $\\NameCert_{\\FinSetUp}$ (\\autoref{ch:concrete-instances-finset-namecert})."),
    (221, "publickey", "PublicKeyUp",
     "The public-key-cryptosystem interface $\\PublicKeyUp$ packages a key-generation, encryption, and decryption triple together with security reductions to a hardness assumption (factoring, discrete logarithm, lattice). It depends on $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert}) and $\\NameCert_{\\NumFieldUp}$ (\\autoref{ch:concrete-instances-numfield-namecert})."),
    (222, "zeroknowledge", "ZeroKnowledgeUp",
     "The zero-knowledge-proof interface $\\ZeroKnowledgeUp$ packages an interactive prover-verifier protocol that is complete, sound, and simulation-paradigm zero-knowledge. It depends on $\\NameCert_{\\HashUp}$ (\\autoref{ch:concrete-instances-hash-namecert}) and $\\NameCert_{\\ComputableUp}$ (\\autoref{ch:concrete-instances-computable-namecert})."),
    (223, "charactertheory", "CharacterTheoryUp",
     "The character-theory interface $\\CharacterTheoryUp$ packages, for a finite group, the trace functions of its irreducible representations together with the orthogonality relations and class-function basis. It depends on $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert}) and $\\NameCert_{\\VecSpaceUp}$ (\\autoref{ch:concrete-instances-vecspace-namecert})."),
    (224, "representationring", "RepresentationRingUp",
     "The representation-ring interface $\\RepresentationRingUp$ packages the Grothendieck ring of finite-dimensional representations of a group under direct sum and tensor product. It depends on $\\NameCert_{\\GroupUp}$ (\\autoref{ch:concrete-instances-group-namecert}) and $\\NameCert_{\\RingUp}$ (\\autoref{ch:concrete-instances-ring-namecert})."),
    (225, "inducedrep", "InducedRepUp",
     "The induced-representation interface $\\InducedRepUp$ packages, for a subgroup inclusion, the induction and restriction functors between representation categories together with Frobenius reciprocity. It depends on $\\NameCert_{\\SubgroupUp}$ (\\autoref{ch:concrete-instances-subgroup-namecert}) and $\\NameCert_{\\RepresentationRingUp}$ (\\autoref{ch:concrete-instances-representationring-namecert})."),
    (226, "vermamodule", "VermaModuleUp",
     "The Verma-module interface $\\VermaModuleUp$ packages, for a semisimple Lie algebra and a highest weight, the universal highest-weight module obtained by inducing from a Borel subalgebra. It depends on $\\NameCert_{\\LieAlgebraUp}$ (\\autoref{ch:concrete-instances-liealgebra-namecert}) and $\\NameCert_{\\RootSystemUp}$ (\\autoref{ch:concrete-instances-rootsystem-namecert})."),
    (227, "hypergeometric", "HypergeometricUp",
     "The hypergeometric-function interface $\\HypergeometricUp$ packages the analytic continuation of $_pF_q$ series defined by ascending-factorial coefficient ratios. It depends on $\\NameCert_{\\ComplexAnalyticUp}$ (\\autoref{ch:concrete-instances-complex-analytic-namecert}) and $\\NameCert_{\\GammaUp}$ (\\autoref{ch:concrete-instances-gamma-namecert})."),
    (228, "bessel", "BesselUp",
     "The Bessel-function interface $\\BesselUp$ packages the holomorphic solutions to Bessel's ODE $x^2 y'' + x y' + (x^2 - n^2) y = 0$, with their integral representations and recurrence laws. It depends on $\\NameCert_{\\OdeUp}$ (\\autoref{ch:concrete-instances-ode-namecert}) and $\\NameCert_{\\HolomorphicUp}$ (\\autoref{ch:concrete-instances-holomorphic-namecert})."),
    (229, "thetafunction", "ThetaFunctionUp",
     "The theta-function interface $\\ThetaFunctionUp$ packages the holomorphic functions $\\theta(z, \\tau)$ on $\\mathbb{C} \\times \\mathbb{H}$ satisfying the heat equation and the lattice-quasiperiodicity laws. It depends on $\\NameCert_{\\HolomorphicUp}$ (\\autoref{ch:concrete-instances-holomorphic-namecert}) and $\\NameCert_{\\EllipticCurveUp}$ (\\autoref{ch:concrete-instances-ellipticcurve-namecert})."),
    (230, "modularform", "ModularFormUp",
     "The modular-form interface $\\ModularFormUp$ packages a holomorphic function on the upper half plane invariant under a congruence subgroup of $SL_2(\\mathbb{Z})$ up to a fixed weight factor. It depends on $\\NameCert_{\\HolomorphicUp}$ (\\autoref{ch:concrete-instances-holomorphic-namecert}) and $\\NameCert_{\\AutomorphicUp}$ (\\autoref{ch:concrete-instances-automorphic-namecert})."),
    (231, "clebschgordan", "ClebschGordanUp",
     "The Clebsch-Gordan interface $\\ClebschGordanUp$ packages, for a pair of irreducible representations of a compact Lie group, the decomposition of their tensor product into irreducibles together with the explicit coupling coefficients. It depends on $\\NameCert_{\\LieGroupUp}$ (\\autoref{ch:concrete-instances-liegroup-namecert}) and $\\NameCert_{\\TensorProductUp}$ (\\autoref{ch:concrete-instances-tensorproduct-namecert})."),
    (232, "knot", "KnotUp",
     "The knot interface $\\KnotUp$ packages an embedding of $S^1$ into $S^3$ up to ambient isotopy, certified by diagrammatic Reidemeister-move equivalence. It depends on $\\NameCert_{\\SOneUp}$ (\\autoref{ch:concrete-instances-s1-namecert}) and $\\NameCert_{\\HomotopyUp}$ (\\autoref{ch:concrete-instances-homotopy-namecert})."),
    (233, "jonespolynomial", "JonesPolynomialUp",
     "The Jones-polynomial interface $\\JonesPolynomialUp$ packages the Laurent polynomial knot invariant in $\\mathbb{Z}[t^{1/2}, t^{-1/2}]$ defined by the skein relation. It depends on $\\NameCert_{\\KnotUp}$ (\\autoref{ch:concrete-instances-knot-namecert}) and $\\NameCert_{\\PolynomialUp}$ (\\autoref{ch:concrete-instances-polynomial-namecert})."),
    (234, "threemanifold", "ThreeManifoldUp",
     "The 3-manifold interface $\\ThreeManifoldUp$ packages a closed orientable manifold of dimension three together with the JSJ and geometric decompositions licensed by Thurston-Perelman geometrisation. It depends on $\\NameCert_{\\ManifoldUp}$ (\\autoref{ch:concrete-instances-manifold-namecert}) and $\\NameCert_{\\TopologyUp}$ (\\autoref{ch:concrete-instances-topology-namecert})."),
    (235, "iwasawa", "IwasawaUp",
     "The Iwasawa-theory interface $\\IwasawaUp$ packages the projective limit of class groups of cyclotomic $\\mathbb{Z}_p$-extensions of a number field together with the Iwasawa main conjecture relating it to a $p$-adic L-function. It depends on $\\NameCert_{\\CyclotomicUp}$ (\\autoref{ch:concrete-instances-cyclotomic-namecert}) and $\\NameCert_{\\IdealClassUp}$ (\\autoref{ch:concrete-instances-idealclass-namecert})."),
    (236, "classfield", "ClassFieldUp",
     "The class-field-theory interface $\\ClassFieldUp$ packages the maximal abelian extension of a number field together with the Artin map sending an idele class to a Frobenius automorphism. It depends on $\\NameCert_{\\NumFieldUp}$ (\\autoref{ch:concrete-instances-numfield-namecert}) and $\\NameCert_{\\AdeleUp}$ (\\autoref{ch:concrete-instances-adele-namecert})."),
    (237, "regulator", "RegulatorUp",
     "The regulator interface $\\RegulatorUp$ packages the determinant of logarithms of fundamental units (for number fields) and its Beilinson generalisation to higher K-theory. It depends on $\\NameCert_{\\DirichletUnitUp}$ (\\autoref{ch:concrete-instances-dirichletunit-namecert}) and $\\NameCert_{\\NumFieldUp}$ (\\autoref{ch:concrete-instances-numfield-namecert})."),
    (238, "stack", "StackUp",
     "The algebraic-stack interface $\\StackUp$ packages a sheaf of groupoids on the étale site of schemes satisfying descent and representability axioms (Artin / Deligne-Mumford). It depends on $\\NameCert_{\\SheafUp}$ (\\autoref{ch:concrete-instances-sheaf-namecert}) and $\\NameCert_{\\SchemeUp}$ (\\autoref{ch:concrete-instances-scheme-namecert})."),
    (239, "stoneduality", "StoneDualityUp",
     "The Stone-duality interface $\\StoneDualityUp$ packages the contravariant equivalence between the category of Boolean algebras and the category of totally disconnected compact Hausdorff spaces. It depends on $\\NameCert_{\\LatticeUp}$ (\\autoref{ch:concrete-instances-lattice-namecert}) and $\\NameCert_{\\TopologyUp}$ (\\autoref{ch:concrete-instances-topology-namecert}), and is a cross-domain bridge witnessing the unified-kernel principle: order theory and topology meet through the same classifier discipline."),
    (240, "gelfandduality", "GelfandDualityUp",
     "The Gelfand-duality interface $\\GelfandDualityUp$ packages the contravariant equivalence between unital commutative C*-algebras and compact Hausdorff spaces, identifying a space with the spectrum of its continuous-function algebra. It depends on $\\NameCert_{\\CStarAlgUp}$ (\\autoref{ch:concrete-instances-cstaralgebra-namecert}) and $\\NameCert_{\\TopologyUp}$ (\\autoref{ch:concrete-instances-topology-namecert}), and witnesses how operator-algebraic and topological certificates share a common spectrum substrate."),
    (241, "pontryaginduality", "PontryaginDualityUp",
     "The Pontryagin-duality interface $\\PontryaginDualityUp$ packages the contravariant self-equivalence on locally compact abelian groups via the Hom-into-circle functor, with the double-dual canonical isomorphism. It depends on $\\NameCert_{\\TopGroupUp}$ (\\autoref{ch:concrete-instances-topgroup-namecert}) and $\\NameCert_{\\AbGroupUp}$ (\\autoref{ch:concrete-instances-abgroup-namecert}), and bridges harmonic-analytic and group-theoretic certificates through the same character classifier."),
    (242, "tannakakrein", "TannakaKreinUp",
     "The Tannaka-Krein interface $\\TannakaKreinUp$ packages the reconstruction of a compact group from its tensor category of finite-dimensional representations together with a fibre functor to vector spaces. It depends on $\\NameCert_{\\LieGroupUp}$ (\\autoref{ch:concrete-instances-liegroup-namecert}) and $\\NameCert_{\\MonoidalCatUp}$ (\\autoref{ch:concrete-instances-monoidalcat-namecert}), and bridges representation theory and category theory through the same fibre-functor classifier."),
    (243, "curryhoward", "CurryHowardUp",
     "The Curry-Howard interface $\\CurryHowardUp$ packages the bijective correspondence between intuitionistic propositions and types, between proofs and programs, and between cut-elimination and reduction. It depends on $\\NameCert_{\\FirstOrderUp}$ (\\autoref{ch:concrete-instances-firstorder-namecert}) and $\\NameCert_{\\LambdaCalcUp}$ (\\autoref{ch:concrete-instances-lambdacalc-namecert}), and bridges logic and computation through the same inductive carrier."),
    (244, "riemannhilbert", "RiemannHilbertUp",
     "The Riemann-Hilbert interface $\\RiemannHilbertUp$ packages the equivalence between regular holonomic D-modules on a complex manifold and perverse sheaves of $\\mathbb{C}$-vector spaces. It depends on $\\NameCert_{\\DerivedFunctorUp}$ (\\autoref{ch:concrete-instances-derivedfunctor-namecert}) and $\\NameCert_{\\SheafUp}$ (\\autoref{ch:concrete-instances-sheaf-namecert}), and bridges differential and topological certificates through a common derived classifier."),
    (245, "koszulduality", "KoszulDualityUp",
     "The Koszul-duality interface $\\KoszulDualityUp$ packages the contravariant derived equivalence between graded algebras of finite global dimension and their Koszul-dual algebras. It depends on $\\NameCert_{\\DerivedCatUp}$ (\\autoref{ch:concrete-instances-derivedcat-namecert}) and $\\NameCert_{\\TensorProductUp}$ (\\autoref{ch:concrete-instances-tensorproduct-namecert}), and bridges algebraic and homological certificates through the same Ext-classifier."),
    (246, "langlands", "LanglandsUp",
     "The Langlands-correspondence interface $\\LanglandsUp$ packages the conjectural bijection between $n$-dimensional Galois representations of a global field and irreducible automorphic representations of $GL_n$ matching local L-factors at almost all places. It depends on $\\NameCert_{\\GaloisGroupUp}$ (\\autoref{ch:concrete-instances-galoisgroup-namecert}) and $\\NameCert_{\\AutomorphicUp}$ (\\autoref{ch:concrete-instances-automorphic-namecert}), and bridges Galois and automorphic certificates through a common $L$-factor classifier."),
    (247, "noethersymmetry", "NoetherSymmetryUp",
     "The Noether-symmetry interface $\\NoetherSymmetryUp$ packages the bijection between continuous symmetries of a Lagrangian and conserved currents along solutions of the Euler-Lagrange equations. It depends on $\\NameCert_{\\LieAlgebraUp}$ (\\autoref{ch:concrete-instances-liealgebra-namecert}) and $\\NameCert_{\\PdeUp}$ (\\autoref{ch:concrete-instances-pde-namecert}), and bridges algebraic and analytic certificates through the same conservation-law ledger."),
    (248, "geomquantization", "GeomQuantizationUp",
     "The geometric-quantization interface $\\GeomQuantizationUp$ packages the construction of a Hilbert space from a symplectic manifold via a prequantum line bundle, polarisation, and metaplectic correction. It depends on $\\NameCert_{\\SymplecticUp}$ (\\autoref{ch:concrete-instances-symplectic-namecert}) and $\\NameCert_{\\HilbertUp}$ (\\autoref{ch:concrete-instances-hilbert-namecert}), and bridges geometric and operator-algebraic certificates through a common polarisation classifier."),
    (249, "deformquantization", "DeformQuantizationUp",
     "The deformation-quantization interface $\\DeformQuantizationUp$ packages the formal star product $\\star_\\hbar$ on a Poisson manifold whose first-order term is the Poisson bracket (Kontsevich formality). It depends on $\\NameCert_{\\SymplecticUp}$ (\\autoref{ch:concrete-instances-symplectic-namecert}) and $\\NameCert_{\\HopfAlgUp}$ (\\autoref{ch:concrete-instances-hopfalg-namecert}), and bridges Poisson and noncommutative certificates through the same formal-deformation classifier."),
    (250, "chernweil", "ChernWeilUp",
     "The Chern-Weil interface $\\ChernWeilUp$ packages the cohomology-class invariants of a principal bundle as polynomial expressions in the curvature form of any chosen connection. It depends on $\\NameCert_{\\CurvatureUp}$ (\\autoref{ch:concrete-instances-curvature-namecert}) and $\\NameCert_{\\DeRhamUp}$ (\\autoref{ch:concrete-instances-deRham-namecert}), and bridges differential and topological certificates through the same characteristic-class classifier."),
    (251, "atiyahsinger", "AtiyahSingerUp",
     "The Atiyah-Singer-index interface $\\AtiyahSingerUp$ packages the equality between the analytic index of an elliptic operator on a closed manifold and a topological index defined via Chern characters and Todd classes. It depends on $\\NameCert_{\\SpectralTheoremUp}$ (\\autoref{ch:concrete-instances-spectraltheorem-namecert}) and $\\NameCert_{\\ChernWeilUp}$ (\\autoref{ch:concrete-instances-chernweil-namecert}), and bridges spectral and topological certificates through the same index pairing."),
    (252, "hodgebridge", "HodgeBridgeUp",
     "The Hodge-bridge interface $\\HodgeBridgeUp$ packages the Hodge decomposition of de Rham cohomology of a compact Kähler manifold into harmonic $(p,q)$-forms together with the Lefschetz / Hard-Lefschetz operators. It depends on $\\NameCert_{\\DeRhamUp}$ (\\autoref{ch:concrete-instances-deRham-namecert}) and $\\NameCert_{\\CohomologyUp}$ (\\autoref{ch:concrete-instances-cohomology-namecert}), and bridges complex-analytic and topological certificates through the harmonic projector."),
    (253, "mirrorsymmetry", "MirrorSymmetryUp",
     "The mirror-symmetry interface $\\MirrorSymmetryUp$ packages, for a Calabi-Yau pair $(X, X^\\vee)$, the conjectural equivalence of the A-model on one side with the B-model on the other (Hodge numbers, Fukaya category vs derived category). It depends on $\\NameCert_{\\SymplecticUp}$ (\\autoref{ch:concrete-instances-symplectic-namecert}) and $\\NameCert_{\\DerivedCatUp}$ (\\autoref{ch:concrete-instances-derivedcat-namecert}), and bridges symplectic and complex-algebraic certificates through a common categorical classifier."),
]

TEMPLATE = """\\chapter{{A Concrete Naming Certificate for $\\{macro}$}}
\\label{{ch:concrete-instances-{slug}-namecert}}

{intro}

\\section{{Carrier definition}}
\\label{{sec:{slug}-carrier}}

\\section{{The certificate}}
\\label{{sec:{slug}-certificate}}
"""


def existing_macros():
    text = PREAMBLE.read_text()
    return set(re.findall(r"\\newcommand\{\\([A-Z][A-Za-z]*Up)\}", text))


def main():
    have = existing_macros()
    missing = []
    inputs = []
    wrote = 0
    for num, slug, macro, intro in CATALOG:
        path = DEST / f"{num}_{slug}_namecert_construction.tex"
        if not path.exists():
            path.write_text(TEMPLATE.format(macro=macro, slug=slug, intro=intro))
            wrote += 1
        inputs.append(f"\\input{{parts/concrete_instances/{num}_{slug}_namecert_construction.tex}}")
        if macro not in have:
            missing.append(macro)
    print("WROTE", wrote, "new files (skipped", len(CATALOG) - wrote, "existing) into", DEST)
    print()
    print("=== INPUT LINES (append to main.tex Concrete Instances part) ===")
    for line in inputs:
        print(line)
    print()
    print("=== MISSING MACROS (add to preamble.tex) ===")
    for m in missing:
        # Convert MacroUp -> mathsf{Body}^uparrow
        body = m[:-2]  # strip "Up"
        print(f"\\newcommand{{\\{m}}}{{\\mathsf{{{body}}}^{{\\uparrow}}}}")


if __name__ == "__main__":
    main()
