import BEDC.MetaCIC.Syntax
import BEDC.MetaCIC.ClosedTerm
import BEDC.MetaCIC.Beta
import BEDC.MetaCIC.Confluence
import BEDC.MetaCIC.Confluence.SourceShapes
import BEDC.MetaCIC.Confluence.Atoms
import BEDC.MetaCIC.Substitution
import BEDC.MetaCIC.Typing
import BEDC.MetaCIC.SubjectReduction
import BEDC.MetaCIC.Normalization
import BEDC.MetaCIC.AtomInfer
import BEDC.MetaCIC.TypedExamples
import BEDC.MetaCIC.PrettyPrint
import BEDC.MetaCIC.BHistSubstrate
