/-
Finite kernel imports are kept separate from derived interface imports.
The kernel boundary is `BEDC.FKernel.*` plus `BEDC.BaseReflection.*`;
`BEDC.Derived.*` modules are licensed objects built over that boundary.
-/

/- Finite kernel. -/
import BEDC.FKernel.Mark
import BEDC.FKernel.Hist
import BEDC.FKernel.Ext
import BEDC.FKernel.Cont
import BEDC.FKernel.Cont.Units
import BEDC.FKernel.Cont.Assoc
import BEDC.FKernel.Cont.AssocSpine
import BEDC.FKernel.Cont.Step
import BEDC.FKernel.Cont.Cancellation
import BEDC.FKernel.Cont.Pattern
import BEDC.FKernel.Cont.VisibleLeft
import BEDC.FKernel.Ask
import BEDC.FKernel.Bundle
import BEDC.FKernel.Bundle.Cancellation
import BEDC.FKernel.Bundle.Length
import BEDC.FKernel.Bundle.MembershipAppend
import BEDC.FKernel.Bundle.ResultInversion
import BEDC.FKernel.Sig
import BEDC.FKernel.Sig.EmptyVisible
import BEDC.FKernel.Sig.Totality
import BEDC.FKernel.Sig.WitnessChain
import BEDC.FKernel.Sig.SameSig
import BEDC.FKernel.Sig.SameSig.Endpoint
import BEDC.FKernel.Sig.SameSig.Equivalence
import BEDC.FKernel.Sig.SameSig.BundlePolicy
import BEDC.FKernel.Sig.Determinacy
import BEDC.FKernel.Sig.Generation
import BEDC.FKernel.Sig.GenerationCommonContext
import BEDC.FKernel.Package
import BEDC.FKernel.Settled
import BEDC.FKernel.ExternalBinary
import BEDC.FKernel.ExternalBinary.BitInversion
import BEDC.FKernel.ExternalBinary.Inversion
import BEDC.FKernel.ExternalBinary.Model
import BEDC.FKernel.ExternalBinary.Cancellation
import BEDC.FKernel.ExternalBinary.Congruence
import BEDC.FKernel.Gap
import BEDC.FKernel.NameCert
import BEDC.FKernel.NameCert.Descent
import BEDC.FKernel.NameCert.StabilityMode
import BEDC.FKernel.Unary
import BEDC.BaseReflection

/- Derived interfaces (licensed objects). -/
import BEDC.Derived.NatUp
import BEDC.Derived.AddUp
import BEDC.Derived.EqtypeUp
import BEDC.Derived.IntUp
import BEDC.Derived.EmptyUp
import BEDC.Derived.UnitUp
import BEDC.Derived.BoolUp
import BEDC.Derived.BoolUpEndpoint
import BEDC.Derived.BoolUp.SemanticCertificate
import BEDC.Derived.OptionUp
import BEDC.Derived.OptionUp.E1Map
import BEDC.Derived.OptionUp.TaggedClassifier
import BEDC.Derived.OptionUp.Determinism
import BEDC.Derived.OptionUp.AbsentSource
import BEDC.Derived.OptionUp.BranchAlignment
import BEDC.Derived.OptionUp.PresentSource
import BEDC.Derived.OptionUp.EmptyRight
import BEDC.Derived.OptionUp.VisibleReadback
import BEDC.Derived.OptionUp.EndpointPairReadback
import BEDC.Derived.OptionUp.VisiblePayloadWitnesses
import BEDC.Derived.OptionUp.E0Source
import BEDC.Derived.OptionUp.ChainPayload
import BEDC.Derived.OptionUp.EmptyRawIff
import BEDC.Derived.OptionUp.LedgerEndpoint
import BEDC.Derived.OptionUp.LedgerReadback
import BEDC.Derived.OptionUp.SourceVisibleIff
import BEDC.Derived.OptionUp.EndpointAbsurd
import BEDC.Derived.OptionUp.EndpointTransportE0Absurd
import BEDC.Derived.OptionUp.BranchExactness
import BEDC.Derived.OptionUp.BranchReadback
import BEDC.Derived.OptionUp.NonemptyBranch
import BEDC.Derived.OptionUp.SourceWeakening
import BEDC.Derived.OptionUp.TaggedPayload
import BEDC.Derived.OptionUp.TaggedCarrier
import BEDC.Derived.OptionUp.CarrierReadback
import BEDC.Derived.OptionUp.Readback
import BEDC.Derived.OptionUp.PayloadDescent
import BEDC.Derived.OptionUp.PayloadDescentCanonicalIntermediate
import BEDC.Derived.OptionUp.PayloadDescentExactness
import BEDC.Derived.OptionUp.PayloadDescentNormalForm
import BEDC.Derived.OptionUp.PayloadDescentImageClassifier
import BEDC.Derived.OptionUp.PayloadDescentSharedReflection
import BEDC.Derived.OptionUp.PayloadDescentCommonTarget
import BEDC.Derived.OptionUp.PayloadDescentImageOccupancy
import BEDC.Derived.OptionUp.PayloadDescentImageVisible
import BEDC.Derived.OptionUp.PayloadDescentImageClassifierReadback
import BEDC.Derived.OptionUp.PayloadDescentImageClassifierIntermediate
import BEDC.Derived.OptionUp.PayloadDescentImageClassifierSelectedVisible
import BEDC.Derived.OptionUp.CompositeNormalizedZeroEndpoint
import BEDC.Derived.OptionUp.PublicEndpointShapeCertificate
import BEDC.Derived.OptionUp.CompositeAbsentPublicFactorization
import BEDC.Derived.OptionUp.StabilityFields
import BEDC.Derived.OptionUp.SemanticCertificate
import BEDC.Derived.OptionUp.VisibleBranchInversion
import BEDC.Derived.OptionUp.CompositeReadback
import BEDC.Derived.OptionUp.SelfExactness
import BEDC.Derived.OptionUp.TransportVisiblePayloadReadback
import BEDC.Derived.OptionUp.ExclusiveBranch
import BEDC.Derived.OptionUp.ExclusiveBranchCarrier
import BEDC.Derived.OptionUp.EndpointFanout
import BEDC.Derived.OptionUp.PayloadFanout
import BEDC.Derived.OptionUp.RightPresentPayloadFanout
import BEDC.Derived.OptionUp.VisibleExclusion
import BEDC.Derived.OptionUp.TaggedConfluence
import BEDC.Derived.OptionUp.AbsentNoPresent
import BEDC.Derived.OptionUp.PayloadDescentSharedTarget
import BEDC.Derived.OptionUp.PrefixClosure
import BEDC.Derived.OptionUp.SuffixClosure
import BEDC.Derived.OptionUp.AppendContext
import BEDC.Derived.OptionUp.PresentChainEndpointClassification
import BEDC.Derived.OptionUp.SourceTransportAbsurd
import BEDC.Derived.OptionUp.CrossAbsentSourceExclusion
import BEDC.Derived.OptionUp.CommonLeftVisiblePayload
import BEDC.Derived.OptionUp.EndpointSemanticFields
import BEDC.Derived.OptionUp.Pattern
import BEDC.Derived.OptionUp.Context
import BEDC.Derived.OptionUpNullableBridge
import BEDC.Derived.ProdUp
import BEDC.Derived.ProdUp.LedgerEndpoint
import BEDC.Derived.ProdUp.SourceMonotonicity
import BEDC.Derived.ProdUp.ComponentwiseRefinement
import BEDC.Derived.ProdUp.PairRepresentation
import BEDC.Derived.ProdUp.Typed
import BEDC.Derived.ProdUp.EmptyLeftComponent
import BEDC.Derived.ComplexUp
import BEDC.Derived.ComplexAnalyticUp
import BEDC.Derived.ComplexDiffUp
import BEDC.Derived.DerivativeUp
import BEDC.Derived.ComplexLimitUp
import BEDC.Derived.ComplexSeriesUp
import BEDC.Derived.RealAnalyticUp
import BEDC.Derived.DirichletSeriesUp
import BEDC.Derived.ZetaBasicUp
import BEDC.Derived.CritStripUp
import BEDC.Derived.ZetaZerosUp
import BEDC.Derived.HolomorphicUp
import BEDC.Derived.HolomorphicUp.IteratedTransport
import BEDC.Derived.HolomorphicUp.IteratedStrict
import BEDC.Derived.ComplexTopologyUp
import BEDC.Derived.ContourIntegralUp
import BEDC.Derived.ResidueUp
import BEDC.Derived.ConvergenceRadiusUp
import BEDC.Derived.GammaUp
import BEDC.Derived.FilterUp
import BEDC.Derived.SumUp
import BEDC.Derived.SumUp.Branch
import BEDC.Derived.SumUp.Classifier
import BEDC.Derived.SumUp.Ledger
import BEDC.Derived.ListUp
import BEDC.Derived.ListUp.AppendContext
import BEDC.Derived.ListUp.CaseExactness
import BEDC.Derived.ListUp.FramedEndpoint
import BEDC.Derived.ListUp.PublicLength
import BEDC.Derived.ListUp.Length
import BEDC.Derived.ListUp.Reverse
import BEDC.Derived.ListUp.SourceEquivalence
import BEDC.Derived.MagmaUp
import BEDC.Derived.SemigroupUp
import BEDC.Derived.MonoidUp
import BEDC.Derived.RatUp
import BEDC.Derived.RatUp.DenominatorAppendDecomposition
import BEDC.Derived.RatUp.DenominatorContext
import BEDC.Derived.RatUp.HistoryClassifier
import BEDC.Derived.RatUp.UnaryContextEndpoint
import BEDC.Derived.RatUp.LedgerContextEquivalence
import BEDC.Derived.StreamNameUp
import BEDC.Derived.PrimeUp
import BEDC.Derived.PrimeUp.NatMulCases
import BEDC.Derived.PadicUp
import BEDC.Derived.RealUp
import BEDC.Derived.RealUp.ReindexedStreamNameBridge
import BEDC.Derived.RealUp.StreamBridge
import BEDC.Derived.RealUp.SemanticCertificate
import BEDC.Derived.RealUp.ReindexedStreamName
import BEDC.Derived.RealUp.EquivalenceFields
import BEDC.Derived.RealUp.PairReadback
import BEDC.Derived.AdeleUp
import BEDC.Derived.AutomorphicUp
import BEDC.Derived.S1Up
import BEDC.Derived.GroupUp
import BEDC.Derived.GroupUp.SingletonEquationSolver
import BEDC.Derived.GroupUp.ConjugationParameter
import BEDC.Derived.GroupUp.ConjugationClassifier
import BEDC.Derived.GroupUp.Commutator
import BEDC.Derived.GroupUp.Centralizer
import BEDC.Derived.GroupUp.CentralizerNormalizer
import BEDC.Derived.GroupUp.CentralizerNormalizerInclusion
import BEDC.Derived.GroupUp.CentralizerNormalizerAutomorphism
import BEDC.Derived.GroupUp.NormalizerSubgroup
import BEDC.Derived.GroupUp.NormalizerRoundtrip
import BEDC.Derived.GroupUp.ProductUnitInverse
import BEDC.Derived.GroupUp.ConjugationEmpty
import BEDC.Derived.GroupUp.ConjugationComposition
import BEDC.Derived.GroupUp.EquationUniqueness
import BEDC.Derived.GroupUp.CancellationIff
import BEDC.Derived.GroupUp.SingletonContext
import BEDC.Derived.GroupUp.SingletonAppendComm
import BEDC.Derived.GroupUp.SingletonAppendContextEmpty
import BEDC.Derived.GroupUp.SingletonContinuation
import BEDC.Derived.GroupUp.SingletonAppendSuffixCancel
import BEDC.Derived.GroupUp.SingletonEquationExact
import BEDC.Derived.GroupUp.SingletonNormalizer
import BEDC.Derived.GroupUp.ContextualContinuationProductUnit
import BEDC.Derived.GroupUp.SuffixProductUnitSplit
import BEDC.Derived.GroupUp.TerminalProduct
import BEDC.Derived.GroupUp.SingletonNormalizerAction
import BEDC.Derived.GroupUp.UnaryAppendInverseObstruction
import BEDC.Derived.GroupUp.NormalizerAction
import BEDC.Derived.GroupUp.NormalizerOrbitActionChain
import BEDC.Derived.GroupUp.EquationCancellationSolver
import BEDC.Derived.GroupUp.ConjugatedCommutatorOrbit
import BEDC.Derived.GroupUp.AppendInverseObstruction
import BEDC.Derived.GroupUp.InverseFiber
import BEDC.Derived.GroupUp.InverseEmpty
import BEDC.Derived.SubgroupUp
import BEDC.Derived.SubgroupUp.RightQuotientClassifier
import BEDC.Derived.SubgroupUp.RightQuotientEmptyFiber
import BEDC.Derived.SubgroupUp.NormalizerCertificate
import BEDC.Derived.SubgroupUp.IntersectionConjugation
import BEDC.Derived.SubgroupUp.IntersectionClassifierClosure
import BEDC.Derived.SubgroupUp.RightCosetTransport
import BEDC.Derived.SubgroupUp.RelativeProduct
import BEDC.Derived.QuotientGroupUp
import BEDC.Derived.AbGroupUp
import BEDC.Derived.HomologyUp
import BEDC.Derived.CohomologyUp
import BEDC.Derived.RingUp
import BEDC.Derived.RingUp.SingletonAppend
import BEDC.Derived.RingUp.Cancellation
import BEDC.Derived.RingUp.ZeroFactor
import BEDC.Derived.RingUp.NegEndpoint
import BEDC.Derived.CommRingUp
import BEDC.Derived.CommRingUp.NegEndpoint
import BEDC.Derived.CommRingUp.EmptyLinearFactor
import BEDC.Derived.CommRingUp.Parallelogram
import BEDC.Derived.CommRingUp.SignedProductBalance
import BEDC.Derived.CommRingUp.CrossTerm
import BEDC.Derived.CommRingUp.SingletonAppend
import BEDC.Derived.CommRingUp.ZeroLinearFactor
import BEDC.Derived.CommRingUp.ZeroLinearFactorExactPackage
import BEDC.Derived.FieldUp
import BEDC.Derived.FieldUp.ConjugationEquation
import BEDC.Derived.FieldUp.EmptyUnitConjugation
import BEDC.Derived.FieldUp.EmptyUnitConjugationFixedPoint
import BEDC.Derived.FieldUp.ContinuationCycle
import BEDC.Derived.FieldUp.RatHistoryClassifierAppendCarrierAbsurd
import BEDC.Derived.FieldUp.SingletonMulEndpoint
import BEDC.Derived.FieldUp.SingletonClassifier
import BEDC.Derived.FieldUp.SingletonContinuation
import BEDC.Derived.FieldUp.AffineEquation
import BEDC.Derived.FieldUp.Affine
import BEDC.Derived.FieldUp.AffineCancellationExactness
import BEDC.Derived.FieldUp.AffineCompositeInverseReverseCoherence
import BEDC.Derived.FieldUp.SingletonAppend
import BEDC.Derived.FieldUp.SingletonAppendPair
import BEDC.Derived.FieldUp.SingletonRatDisjoint
import BEDC.Derived.FieldUp.RatBoundary
import BEDC.Derived.FieldUp.Nonzero
import BEDC.Derived.FieldUp.InverseInvolutiveNonzero
import BEDC.Derived.FieldUp.InverseApartness
import BEDC.Derived.FieldUp.InverseClassifier
import BEDC.Derived.FieldUp.ProductApartness
import BEDC.Derived.FieldUp.SquareApartness
import BEDC.Derived.FieldUp.SignedFactor
import BEDC.Derived.FieldUp.InverseProductReverseNonzero
import BEDC.Derived.FieldUp.InverseProductRightApartness
import BEDC.Derived.FieldUp.InverseAutomorphism
import BEDC.Derived.FieldUp.SquareApartnessAndAffine
import BEDC.Derived.FieldUp.TwoSided
import BEDC.Derived.FieldUp.TwoSidedEmptySolution
import BEDC.Derived.FieldUp.NestedProduct
import BEDC.Derived.FieldUp.RatDenomUnit
import BEDC.Derived.FieldUp.RatDenomUnitResultEmpty
import BEDC.Derived.FieldUp.RatContinuationSemigroupPackage
import BEDC.Derived.FieldUp.RatContinuationObstructionPackage
import BEDC.Derived.FieldUp.RatDenomUnitCarrierVisibleCases
import BEDC.Derived.FieldUp.RatDenomUnitSemantic
import BEDC.Derived.FieldUp.RatDenomUnitEndpointAbsurd
import BEDC.Derived.FieldUp.RatDenomUnitAppendRat
import BEDC.Derived.FieldUp.RatDenomUnitStrictProduct
import BEDC.Derived.FieldUp.RatDenomUnitEmptyContext
import BEDC.Derived.FieldUp.RatDenomUnitProductNonemptyComm
import BEDC.Derived.FieldUp.RatDenomUnitContextualProduct
import BEDC.Derived.FieldUp.RatContinuation
import BEDC.Derived.FieldUp.RatContinuationLeftClosed
import BEDC.Derived.FieldUp.RatContinuationTail
import BEDC.Derived.FieldUp.RatContinuationE1LeftUnitLawAbsurd
import BEDC.Derived.FieldUp.RatContinuationVisibleLeftUnitLawAbsurd
import BEDC.Derived.FieldUp.RatContinuationLeftUnitResult
import BEDC.Derived.FieldUp.RatContinuationOneSidedUnit
import BEDC.Derived.FieldUp.RatContextInvariantObstruction
import BEDC.Derived.FieldUp.RatContinuationAppendComm
import BEDC.Derived.FieldUp.RatContinuationCommutative
import BEDC.Derived.FieldUp.RatDenominatorUnitEnvelopeContinuation
import BEDC.Derived.FieldUp.DenominatorUnitEnvelope
import BEDC.Derived.FieldUp.DenominatorUnitEnvelopeBilateralContext
import BEDC.Derived.FieldUp.DenominatorUnitEnvelopeEmptyContext
import BEDC.Derived.FieldUp.DenominatorUnitEnvelopeNormalForm
import BEDC.Derived.FieldUp.DenominatorUnitEnvelopeProductStrictSupport
import BEDC.Derived.FieldUp.ProductRightEquation
import BEDC.Derived.FieldUp.ProductInverseClassifier
import BEDC.Derived.FieldUp.ProductWitnessIndependence
import BEDC.Derived.FieldUp.AffineCompositeProductWitnessIndependence
import BEDC.Derived.FieldUp.InverseEmptyTransport
import BEDC.Derived.FieldUp.EquationUniqueness
import BEDC.Derived.FieldUp.RatContinuationExternalBoundary
import BEDC.Derived.FieldUp.RatCanonicalEndpoint
import BEDC.Derived.FieldUp.PositiveDenominatorAppendSplit
import BEDC.Derived.FieldUp.EmptyOffsetComposition
import BEDC.Derived.FieldUp.ContextualAction
import BEDC.Derived.FieldUp.ContextualActionEmptyContextTransport
import BEDC.Derived.FieldUp.ContextualActionEmptyUnit
import BEDC.Derived.FieldUp.ContextualActionNormalizedPair
import BEDC.Derived.FieldUp.ContextualActionStrictSupport
import BEDC.Derived.FieldUp.RatDenomContextPair
import BEDC.Derived.FieldUp.ContextualActionPair
import BEDC.Derived.FieldUp.EmptyUnitCancellation
import BEDC.Derived.FieldUp.EmptyContextCancel
import BEDC.Derived.FieldUp.SingletonContinuationLeftEndpoint
import BEDC.Derived.FieldUp.SingletonContinuationRightEndpoint
import BEDC.Derived.FieldUp.SingletonClassifierEndpointTransport
import BEDC.Derived.FieldUp.SingletonContinuationContextTransport
import BEDC.Derived.FieldUp.SingletonContinuationCommIff
import BEDC.Derived.FieldUp.SingletonContinuationAppendSplit
import BEDC.Derived.FieldUp.SingletonCycleTailClassifier
import BEDC.Derived.FieldUp.SingletonNonZeroReadback
import BEDC.Derived.FieldUp.SingletonAppendSuffixCancel
import BEDC.Derived.FieldUp.SingletonOperationContext
import BEDC.Derived.FieldUp.SingletonOperationContextNonZero
import BEDC.Derived.FieldUp.SingletonAddMulContext
import BEDC.Derived.FieldUp.SingletonAddNegZeroContextContinuation
import BEDC.Derived.FieldUp.SingletonNegContextContinuationClassifier
import BEDC.Derived.FieldUp.SingletonMulInvContextContinuationClassifier
import BEDC.Derived.FieldUp.SingletonCarrierPartition
import BEDC.Derived.FieldUp.SingletonContextBoundary
import BEDC.Derived.FieldUp.SingletonAppendContextVisibleMiddle
import BEDC.Derived.FieldUp.RatRightAppendFixedAbsurd
import BEDC.Derived.FieldUp.NondegenerateSemanticExit
import BEDC.Derived.FieldUp.RatRightNestedContextualBoundary
import BEDC.Derived.FieldUp.RatBracketingCrossEndpoint
import BEDC.Derived.FieldUp.RatBracketingSelector
import BEDC.Derived.FieldUp.RatHistoryClassifierContextEndpoints
import BEDC.Derived.FieldUp.RatHistoryClassifierContinuationResultSingletonAbsurd
import BEDC.Derived.FieldUp.RatClassifiedFactors
import BEDC.Derived.FieldUp.RatContinuationTwoSidedUnit
import BEDC.Derived.FieldUp.AlgebraReductCompatibility
import BEDC.Derived.FieldUp.TailFactor
import BEDC.Derived.RatUp.HistoryLedgerContextEndpoint
import BEDC.Derived.FieldUp.RatDenomUnitContextEndpoint
import BEDC.Derived.EquivCatUp
import BEDC.Derived.FuncobjUp
import BEDC.Derived.FpsUp
import BEDC.Derived.LinearMapUp
import BEDC.Derived.ModuleUp
import BEDC.Derived.TensorProductUp
import BEDC.Derived.VecSpaceUp
import BEDC.Derived.MatrixUp
import BEDC.Derived.DeterminantUp
import BEDC.Derived.EigenUp
import BEDC.Derived.PolynomialUp
import BEDC.Derived.PreorderUp
import BEDC.Derived.LatticeUp
import BEDC.Derived.IntervalUp
import BEDC.Derived.MetricUp
import BEDC.Derived.MetricUp.DepthZero
import BEDC.Derived.MetricUp.BoundaryExactness
import BEDC.Derived.MetricUp.DepthClassifier
import BEDC.Derived.MetricUp.LeftE1Result
import BEDC.Derived.MetricUp.RightE1ResultShape
import BEDC.Derived.MetricUp.Triangle
import BEDC.Derived.MetricUp.EmptyBoundaryDistance
import BEDC.Derived.MetricUp.Transport
import BEDC.Derived.MetricUp.ContDepthAdd
import BEDC.Derived.MetricUp.VisibleContextSemantic
import BEDC.Derived.MetricUp.PrefixIndependentSymmetric
import BEDC.Derived.MetricUp.HsameDeterminism
import BEDC.Derived.MetricUp.AppendCommPackage
import BEDC.Derived.CompletionUp
import BEDC.Derived.ContinuousUp
import BEDC.Derived.ContinuousUp.Suffix
import BEDC.Derived.ContinuousUp.GraphChainFactorization
import BEDC.Derived.ContinuousUp.ModulusWitnessDeterminism
import BEDC.Derived.ContinuousUp.ModulusWitnessPublicReadback
import BEDC.Derived.ContinuousUp.EmptyMap
import BEDC.Derived.ContinuousUp.ResultCases
import BEDC.Derived.ContinuousUp.EmptySource
import BEDC.Derived.ContinuousUp.EmptyModulus
import BEDC.Derived.ContinuousUp.EmptyTarget
import BEDC.Derived.ContinuousUp.Transport
import BEDC.Derived.ContinuousUp.CompModulusChain
import BEDC.Derived.ContinuousUp.CompositeEndpointTransport
import BEDC.Derived.ContinuousUp.EndpointCycle
import BEDC.Derived.ContinuousUp.GraphModulusReadback
import BEDC.Derived.ContinuousMapUp
import BEDC.Derived.CompactUp
import BEDC.Derived.CompactUp.CommonPrecision
import BEDC.Derived.CompactUp.Suffix
import BEDC.Derived.CompactUp.ContinuationWitness
import BEDC.Derived.CompactUp.EndpointIff
import BEDC.Derived.CompactUp.LocatedEndpointPackage
import BEDC.Derived.CompactUp.InitialEndpointsUnary
import BEDC.Derived.CompactUp.PrefixedCompositeMiddle
import BEDC.Derived.CompactUp.RefinementPrefix
import BEDC.Derived.CompactUp.PrefixedCompositePrefixIndependent
import BEDC.Derived.CompactUp.SemanticCertificate
import BEDC.Derived.CompactUp.EmptyFinalReflection
import BEDC.Derived.CompactUp.NonemptyForward
import BEDC.Derived.CompactUp.EmptyNet
import BEDC.Derived.CompactUp.EmptyCenter
import BEDC.Derived.CompactUp.LeftE1ResultCases
import BEDC.Derived.CompactUp.EndpointCycle
import BEDC.Derived.CategoryUp
import BEDC.Derived.CategoryUp.E1TargetMorphismExactness
import BEDC.Derived.CategoryUp.NonemptyMorphismIff
import BEDC.Derived.CategoryUp.MorphismEmptyEndpoint
import BEDC.Derived.CategoryUp.MorphismEndpointInduction
import BEDC.Derived.CategoryUp.EndpointCycle
import BEDC.Derived.CategoryUp.ContinuationTailIdentitySquare
import BEDC.Derived.CategoryUp.SemanticCertificate
import BEDC.Derived.CategoryUp.IdentityLaw
import BEDC.Derived.CategoryUp.Cycle
import BEDC.Derived.CategoryUp.PrefixCycle
import BEDC.Derived.CategoryUp.SourceEmpty
import BEDC.Derived.CategoryUp.Prefix
import BEDC.Derived.CategoryUp.ContinuationCertificate
import BEDC.Derived.CategoryUp.TailCommClosed
import BEDC.Derived.CategoryUp.CompDeterminism
import BEDC.Derived.CategoryUp.CompTailExact
import BEDC.Derived.CategoryUp.CompFactorIff
import BEDC.Derived.CategoryUp.EndpointMiddleDeterminism
import BEDC.Derived.CategoryUp.EmptyMorphism
import BEDC.Derived.CategoryUp.EmptyComposite
import BEDC.Derived.CategoryUp.CompTransport
import BEDC.Derived.CategoryUp.EmptySourceComposite
import BEDC.Derived.CategoryUp.EmptySourceCompositeEndpoint
import BEDC.Derived.CategoryUp.EmptySourceSwap
import BEDC.Derived.CategoryUp.EmptyMiddleInversion
import BEDC.Derived.CategoryUp.ContinuationBoundary
import BEDC.Derived.CategoryUp.FactorTail
import BEDC.Derived.CategoryUp.CompositeEmptyTail
import BEDC.Derived.CategoryUp.HomContinuation
import BEDC.Derived.CategoryUp.CompCycleResult
import BEDC.Derived.CategoryUp.LawPackage
import BEDC.Derived.CategoryUp.EmptySourceTail
import BEDC.Derived.CategoryUp.StabilityLawPackage
import BEDC.Derived.CategoryUp.TargetCases
import BEDC.Derived.CategoryUp.EmptySourceE1TargetPayload
import BEDC.Derived.CategoryUp.TargetDescent
import BEDC.Derived.CategoryUp.ZeroHeadedComponent
import BEDC.Derived.CategoryUp.HomContinuationTail
import BEDC.Derived.CategoryUp.ContinuationBridge
import BEDC.Derived.CategoryUp.EndomorphismTail
import BEDC.Derived.CategoryUp.VisibleTailResult
import BEDC.Derived.CategoryUp.RightVisibleTailEmpty
import BEDC.Derived.CategoryUp.NonemptyCases
import BEDC.Derived.CategoryUp.NonemptyResultVisibleHomReadback
import BEDC.Derived.CategoryUp.CompResultNonemptySourceTargetCases
import BEDC.Derived.CategoryUp.RightTailFactorization
import BEDC.Derived.CategoryUp.LeftTailFixedIdentity
import BEDC.Derived.CategoryUp.RightTailFixedIdentity
import BEDC.Derived.CategoryUp.LeftTailResult
import BEDC.Derived.CategoryUp.ContLeftE1Result
import BEDC.Derived.CategoryUp.EmptySourceVisibleTargetTail
import BEDC.Derived.CategoryUp.UnaryTailZero
import BEDC.Derived.CategoryUp.E1SourceCompTargetVisible
import BEDC.Derived.CategoryUp.SourceMorphismCasesIff
import BEDC.Derived.CategoryUp.NonemptyTargetCarrierCases
import BEDC.Derived.CategoryUp.EndpointCycleTailEmptyIff
import BEDC.Derived.CategoryUp.TailCarrierAlignment
import BEDC.Derived.CategoryUp.NonemptyTailResultDescent
import BEDC.Derived.CategoryUp.TargetSourceCasesIff
import BEDC.Derived.CategoryUp.NonemptyMorphismSourceCases
import BEDC.Derived.CategoryUp.NonemptyMorphismEndpointCases
import BEDC.Derived.CategoryUp.NonemptyMorphismTargetVisible
import BEDC.Derived.CategoryUp.E1NonemptyMorphismUnique
import BEDC.Derived.CategoryUp.E1PayloadDeterminism
import BEDC.Derived.CategoryUp.EndpointVisible
import BEDC.Derived.CategoryUp.RightUnaryTailPublicReadback
import BEDC.Derived.CategoryUp.TailCommCongr
import BEDC.Derived.CategoryUp.RightE1TailTargetCases
import BEDC.Derived.CategoryUp.CompTargetEmptyIff
import BEDC.Derived.CategoryUp.CompSourceEmptyTailTargetIff
import BEDC.Derived.CategoryUp.CompTailSemanticCertificate
import BEDC.Derived.CategoryUp.RightE0TailTargetCases
import BEDC.Derived.CategoryUp.CompMiddleTransport
import BEDC.Derived.FunctorUp
import BEDC.Derived.FunctorUp.PrefixCarrier
import BEDC.Derived.FunctorUp.SemanticCertificate
import BEDC.Derived.FunctorUp.RightUnaryTailPublicReadback
import BEDC.Derived.FunctorUp.FamilyReadback
import BEDC.Derived.FunctorUp.IdentitySquare
import BEDC.Derived.FunctorUp.ZeroHeadedComposition
import BEDC.Derived.FunctorUp.CompMiddlePrefix
import BEDC.Derived.FunctorUp.CycleEmptyComponents
import BEDC.Derived.NatTransUp
import BEDC.Derived.NatTransUp.EmptyVertComp
import BEDC.Derived.NatTransUp.E1ObjectEmptyComponent
import BEDC.Derived.NatTransUp.E1TargetEmptyComponent
import BEDC.Derived.NatTransUp.EmptyComponentSemantic
import BEDC.Derived.NatTransUp.FamilyReadback
import BEDC.Derived.NatTransUp.IdentitySquare
import BEDC.Derived.NatTransUp.ZeroHeadedComposition
import BEDC.Derived.NatTransUp.VertCycleEmptyComponents
import BEDC.Derived.AdjunctionUp
import BEDC.Derived.YonedaUp
import BEDC.Derived.LFunctionUp
import BEDC.Derived.MonadUp
import BEDC.Derived.InterHist
import BEDC.Derived.Observer
import BEDC.Derived.FieldUp.RatExternalUnitSeparation
import BEDC.Derived.FieldUp.RatDenominatorExternalUnitNormalForm
import BEDC.Reflection
